<a href="https://colab.research.google.com/github/joyangelai/Colabs/blob/main/cohort2_pandas1_tutorial_Joy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas

In [ ]:
#Import pandas and numpy
import pandas as pd # for data manipulation and analysis
import numpy as np # used for mathematical computation # built on top of pandas

Data stractures used in pandas
1. pandas series
2. pandas data Frame

In [ ]:
#Create a  num and str list and convert it to a series
a = ["car","boat", "bike"]  #list
series1 = pd.Series(a)
print(series1)

0     car
1    boat
2    bike
dtype: object

In [ ]:
#create a list and convert it to a dataframe
a = [("car",100),("boat",70), ("bike",40)]
df = pd.DataFrame(a, columns=("item","price"))
print(df)
type(df)

   item  price
0   car    100
1  boat     70
2  bike     40

pandas.core.frame.DataFrame

In [ ]:
#saving the dataframe above to csv file
df.to_csv("item.csv", index= None)

In [ ]:
#loading the saved item dataset
df2 = pd.read_csv("item.csv")
df2

   item  price
0   car    100
1  boat     70
2  bike     40

In [ ]:
#prove that the dataframe is made up of more than one series
df_price = df['price']
type(df_price)

pandas.core.series.Series

## Reading from files

In [ ]:
#Loading the dataset #excel dataset
data = pd.read_excel('Sample_Superstore.xlsx')
data

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,...,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
0,18606,Not Specified,0.01,2.88,0.50,2,Janice Fletcher,Regular Air,Corporate,Office Supplies,...,Central,Illinois,Addison,60101,2012-05-28,2012-05-30,1.320000,2,5.90,88525
1,20847,High,0.01,2.84,0.93,3,Bonnie Potter,Express Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221,2010-07-07,2010-07-08,4.560000,4,13.01,88522
2,23086,Not Specified,0.03,6.68,6.15,3,Bonnie Potter,Express Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221,2011-07-27,2011-07-28,-47.640000,7,49.92,88523
3,23087,Not Specified,0.01,5.68,3.60,3,Bonnie Potter,Regular Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221,2011-07-27,2011-07-28,-30.510000,7,41.64,88523
4,23088,Not Specified,0.00,205.99,2.50,3,Bonnie Potter,Express Air,Corporate,Technology,...,West,Washington,Anacortes,98221,2011-07-27,2011-07-27,998.202300,8,1446.67,88523
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9421,20275,Critical,0.06,35.89,14.72,3402,Frederick Cole,Regular Air,Consumer,Office Supplies,...,East,West Virginia,Charleston,25314,2013-05-14,2013-05-15,137.860000,13,447.87,87532
9422,20276,Critical,0.00,3.34,7.49,3402,Frederick Cole,Regular Air,Consumer,Office Supplies,...,East,West Virginia,Charleston,25314,2013-05-14,2013-05-14,-39.070000,3,13.23,87532
9423,24491,Not Specified,0.08,550.98,45.70,3402,Frederick Cole,Delivery Truck,Consumer,Furniture,...,East,West Virginia,Charleston,25314,2013-09-12,2013-09-14,-1225.029097,4,2215.93,87533
9424,25914,High,0.10,105.98,13.99,3403,Tammy Buckley,Express Air,Consumer,Furniture,...,West,Wyoming,Cheyenne,82001,2010-02-08,2010-02-11,349.485000,5,506.50,87530
9425,24492,Not Specified,0.09,7.78,2.50,3403,Tammy Buckley,Express Air,Consumer,Office Supplies,...,West,Wyoming,Cheyenne,82001,2013-09-12,2013-09-14,78.062400,23,172.48,87533

## Writing to files

In [ ]:
#saving the file to csv # use to_csv() and set index = False
data.to_csv("superstore.csv", index= None)

## Dataframe basics

In [ ]:
#setting the default data view # pd.set_option("display.max_columns", 500)
pd.set_option("display.max_columns",200)

In [ ]:
#display data
data

NameError: name 'data' is not defined

In [ ]:
#checking a few top rows
data.head()

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,Product Sub-Category,Product Container,Product Name,Product Base Margin,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
0,18606,Not Specified,0.01,2.88,0.50,2,Janice Fletcher,Regular Air,Corporate,Office Supplies,Labels,Small Box,Avery 49,0.36,Central,Illinois,Addison,60101,2012-05-28,2012-05-30,1.3200,2,5.90,88525
1,20847,High,0.01,2.84,0.93,3,Bonnie Potter,Express Air,Corporate,Office Supplies,Pens & Art Supplies,Wrap Bag,SANFORD Liquid Accent™ Tank-Style Highlighters,0.54,West,Washington,Anacortes,98221,2010-07-07,2010-07-08,4.5600,4,13.01,88522
2,23086,Not Specified,0.03,6.68,6.15,3,Bonnie Potter,Express Air,Corporate,Office Supplies,Paper,Small Box,Xerox 1968,0.37,West,Washington,Anacortes,98221,2011-07-27,2011-07-28,-47.6400,7,49.92,88523
3,23087,Not Specified,0.01,5.68,3.60,3,Bonnie Potter,Regular Air,Corporate,Office Supplies,"Scissors, Rulers and Trimmers",Small Pack,Acme® Preferred Stainless Steel Scissors,0.56,West,Washington,Anacortes,98221,2011-07-27,2011-07-28,-30.5100,7,41.64,88523
4,23088,Not Specified,0.00,205.99,2.50,3,Bonnie Potter,Express Air,Corporate,Technology,Telephones and Communication,Small Box,V70,0.59,West,Washington,Anacortes,98221,2011-07-27,2011-07-27,998.2023,8,1446.67,88523

In [ ]:
#IDA

In [ ]:
#Displaying the top 3 rows #
data.head(3)

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,Product Sub-Category,Product Container,Product Name,Product Base Margin,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
0,18606,Not Specified,0.01,2.88,0.50,2,Janice Fletcher,Regular Air,Corporate,Office Supplies,Labels,Small Box,Avery 49,0.36,Central,Illinois,Addison,60101,2012-05-28,2012-05-30,1.32,2,5.90,88525
1,20847,High,0.01,2.84,0.93,3,Bonnie Potter,Express Air,Corporate,Office Supplies,Pens & Art Supplies,Wrap Bag,SANFORD Liquid Accent™ Tank-Style Highlighters,0.54,West,Washington,Anacortes,98221,2010-07-07,2010-07-08,4.56,4,13.01,88522
2,23086,Not Specified,0.03,6.68,6.15,3,Bonnie Potter,Express Air,Corporate,Office Supplies,Paper,Small Box,Xerox 1968,0.37,West,Washington,Anacortes,98221,2011-07-27,2011-07-28,-47.64,7,49.92,88523

In [ ]:
#Displaying the last 3 rows #
data.tail(3)

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,Product Sub-Category,Product Container,Product Name,Product Base Margin,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
9423,24491,Not Specified,0.08,550.98,45.70,3402,Frederick Cole,Delivery Truck,Consumer,Furniture,Tables,Jumbo Box,Chromcraft Bull-Nose Wood Oval Conference Tabl...,0.71,East,West Virginia,Charleston,25314,2013-09-12,2013-09-14,-1225.029097,4,2215.93,87533
9424,25914,High,0.10,105.98,13.99,3403,Tammy Buckley,Express Air,Consumer,Furniture,Office Furnishings,Medium Box,"Tenex 46"" x 60"" Computer Anti-Static Chairmat,...",0.65,West,Wyoming,Cheyenne,82001,2010-02-08,2010-02-11,349.485000,5,506.50,87530
9425,24492,Not Specified,0.09,7.78,2.50,3403,Tammy Buckley,Express Air,Consumer,Office Supplies,Envelopes,Small Box,Staples #10 Colored Envelopes,0.38,West,Wyoming,Cheyenne,82001,2013-09-12,2013-09-14,78.062400,23,172.48,87533

In [ ]:
#Displaying 3 random rows #use sample()
data.sample(4)

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,Product Sub-Category,Product Container,Product Name,Product Base Margin,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
2022,21110,Low,0.00,20.99,3.30,759,Bernice F Day,Regular Air,Small Business,Technology,Telephones and Communication,Small Pack,Accessory39,0.81,Central,Illinois,Quincy,62301,2010-05-29,2010-06-05,-92.961,5,92.96,86639
9087,24053,Medium,0.01,145.98,51.92,3284,Michael Shaffer,Delivery Truck,Consumer,Furniture,Tables,Jumbo Box,Bevis Rectangular Conference Tables,0.69,South,Florida,Kissimmee,34741,2013-06-10,2013-06-12,176.526,1,166.16,90761
6480,21171,Critical,0.10,130.98,30.00,2385,Janice Frye,Delivery Truck,Small Business,Furniture,Chairs & Chairmats,Jumbo Drum,Office Star - Contemporary Task Swivel chair w...,0.78,West,New Mexico,Las Cruces,88001,2010-05-22,2010-05-24,-592.430,18,2259.99,89184
4222,19549,Critical,0.08,5.98,3.85,1588,Terri Justice Gardner,Regular Air,Corporate,Technology,Computer Peripherals,Small Pack,"Imation 3.5"" IBM-Formatted Diskettes, 10/Pack",0.68,East,Ohio,East Cleveland,44112,2013-03-30,2013-04-01,-95.170,9,53.92,90283

In [ ]:
#checking the columns # use columns attribute
data.columns

Index(['Row ID', 'Order Priority', 'Discount', 'Unit Price', 'Shipping Cost',
       'Customer ID', 'Customer Name', 'Ship Mode', 'Customer Segment',
       'Product Category', 'Product Sub-Category', 'Product Container',
       'Product Name', 'Product Base Margin', 'Region', 'State or Province',
       'City', 'Postal Code', 'Order Date', 'Ship Date', 'Profit',
       'Quantity ordered new', 'Sales', 'Order ID'],
      dtype='object')

In [ ]:
#checking the index # use df.index
data.index

RangeIndex(start=0, stop=9426, step=1)

In [ ]:
#to check the shape
data.shape
print(f"This dataset has {data.shape[0]} records and {data.shape[1]} columns")

This dataset has 9426 records and 24 columns

In [ ]:
#to also get number of records
len(data)

9426

## Dataframe summary

In [ ]:
#Checking the data Summary # use info(), we can also use info(verbose=False)
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9426 entries, 0 to 9425
Data columns (total 24 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Row ID                9426 non-null   int64
 1   Order Priority        9426 non-null   object
 2   Discount              9426 non-null   float64
 3   Unit Price            9426 non-null   float64
 4   Shipping Cost         9426 non-null   float64
 5   Customer ID           9426 non-null   int64
 6   Customer Name         9426 non-null   object
 7   Ship Mode             9426 non-null   object
 8   Customer Segment      9426 non-null   object
 9   Product Category      9426 non-null   object
 10  Product Sub-Category  9426 non-null   object
 11  Product Container     9426 non-null   object
 12  Product Name          9426 non-null   object
 13  Product Base Margin   9354 non-null   float64
 14  Region                9426 non-null   object
 15  State or Province     9426 non-null   object
 16  City                  9426 non-null   object
 17  Postal Code           9426 non-null   int64
 18  Order Date            9426 non-null   datetime64[ns]
 19  Ship Date             9426 non-null   datetime64[ns]
 20  Profit                9426 non-null   float64
 21  Quantity ordered new  9426 non-null   int64
 22  Sales                 9426 non-null   float64
 23  Order ID              9426 non-null   int64
dtypes: datetime64[ns](2), float64(6), int64(5), object(11)
memory usage: 1.7+ MB

In [ ]:
#incorporating verbose argument
data.info(verbose=False)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9426 entries, 0 to 9425
Columns: 24 entries, Row ID to Order ID
dtypes: datetime64[ns](2), float64(6), int64(5), object(11)
memory usage: 1.7+ MB

In [ ]:
#Checking concise Descriptive statistics for numerical variables# use .describe
data.describe().T

,count,mean,min,25%,50%,75%,max,std
Row ID,9426.0,20241.015277,2.0,19330.25,21686.5,24042.75,26399.0,6101.890965
Discount,9426.0,0.049628,0.0,0.02,0.05,0.08,0.25,0.031798
Unit Price,9426.0,88.303686,0.99,6.48,20.99,85.99,6783.02,281.540982
Shipping Cost,9426.0,12.795142,0.49,3.1925,6.05,13.99,164.73,17.181203
Customer ID,9426.0,1738.422236,2.0,898.0,1750.0,2578.75,3403.0,979.167197
Product Base Margin,9354.0,0.512189,0.35,0.38,0.52,0.59,0.85,0.135229
Postal Code,9426.0,52446.327286,1001.0,29406.0,52302.0,78516.0,99362.0,29374.597802
Order Date,9426,2012-03-05 18:33:59.465308672,2010-01-01 00:00:00,2011-03-07 06:00:00,2012-04-08 00:00:00,2013-03-26 00:00:00,2013-12-31 00:00:00,NaN
Ship Date,9426,2012-03-07 19:16:18.485041408,2010-01-02 00:00:00,2011-03-09 00:00:00,2012-04-09 00:00:00,2013-03-28 00:00:00,2014-01-17 00:00:00,NaN
Profit,9426.0,139.23641,-16476.838,-74.017375,2.5676,140.24385,16332.414,998.486483
Quantity ordered new,9426.0,13.79843,1.0,5.0,10.0,17.0,170.0,15.107688
Sales,9426.0,949.706272,1.32,61.2825,203.455,776.4025,100119.16,2598.019818
Order ID,9426.0,82318.489073,6.0,86737.25,88344.5,89987.75,91591.0,19149.448857

In [ ]:
#Checking concise Descriptive statistics for categorical variables# use coln.describe()
#data.describe(include=(["float","int"]))
data.describe(include = 'O') #you can use object instead of capital 'O'

,Order Priority,Customer Name,Ship Mode,Customer Segment,Product Category,Product Sub-Category,Product Container,Product Name,Region,State or Province,City
count,9426,9426,9426,9426,9426,9426,9426,9426,9426,9426,9426
unique,6,2703,3,4,3,17,7,1263,4,49,1424
top,High,Louis Parrish,Regular Air,Corporate,Office Supplies,Paper,Small Box,"Global High-Back Leather Tilter, Burgundy",Central,California,New York City
freq,1970,27,7036,3375,5181,1379,4887,27,2899,1021,202

In [ ]:
data["Ship Mode"].unique()

array(['Regular Air', 'Express Air', 'Delivery Truck'], dtype=object)

In [ ]:
#checking the number of variables and records, use .shape,   or len()
data.shape()
#len(data)

TypeError: 'tuple' object is not callable

## Subsetting Columns

This is the act of selecting  a few columns from the entire dataframe.

In [ ]:
# Selecting a single column using []
data_discount = data['Discount']
print(type(data_discount))
data_discount.head()

<class 'pandas.core.series.Series'>

0    0.01
1    0.01
2    0.03
3    0.01
4    0.00
Name: Discount, dtype: float64

In [ ]:
#selecting single column discount and making it a data frame, use [[]]
data_discount = data[['Discount']]
print(type(data_discount))
data_discount.head()

<class 'pandas.core.frame.DataFrame'>

   Discount
0      0.01
1      0.01
2      0.03
3      0.01
4      0.00

In [ ]:
#another way of selecting a single column without whitespace
data_discount = data.Discount
data_discount

0       0.01
1       0.01
2       0.03
3       0.01
4       0.00
        ...
9421    0.06
9422    0.00
9423    0.08
9424    0.10
9425    0.09
Name: Discount, Length: 9426, dtype: float64

In [ ]:
#selcting the specific columns# use df[['col1', 'col2', 'col3']] e.g. selsct Order Date, Product Date, and ship mode
df_sub2 = data[['Order Priority', 'Discount', 'Unit Price','Shipping Cost']]
df_sub2.head()

  Order Priority  Discount  Unit Price  Shipping Cost
0  Not Specified      0.01        2.88           0.50
1           High      0.01        2.84           0.93
2  Not Specified      0.03        6.68           6.15
3  Not Specified      0.01        5.68           3.60
4  Not Specified      0.00      205.99           2.50

In [ ]:
# we can use slicing as well e.g. df[df.columns[:5]]
data[data.columns[4:11]]

,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,Product Sub-Category
0,0.50,2,Janice Fletcher,Regular Air,Corporate,Office Supplies,Labels
1,0.93,3,Bonnie Potter,Express Air,Corporate,Office Supplies,Pens & Art Supplies
2,6.15,3,Bonnie Potter,Express Air,Corporate,Office Supplies,Paper
3,3.60,3,Bonnie Potter,Regular Air,Corporate,Office Supplies,"Scissors, Rulers and Trimmers"
4,2.50,3,Bonnie Potter,Express Air,Corporate,Technology,Telephones and Communication
...,...,...,...,...,...,...,...
9421,14.72,3402,Frederick Cole,Regular Air,Consumer,Office Supplies,Envelopes
9422,7.49,3402,Frederick Cole,Regular Air,Consumer,Office Supplies,Pens & Art Supplies
9423,45.70,3402,Frederick Cole,Delivery Truck,Consumer,Furniture,Tables
9424,13.99,3403,Tammy Buckley,Express Air,Consumer,Furniture,Office Furnishings
9425,2.50,3403,Tammy Buckley,Express Air,Consumer,Office Supplies,Envelopes

In [ ]:
#Using list comprehnsion e.g df[[c for c in df.columns]]
data[[i for i in data.columns]]

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,Product Sub-Category,Product Container,Product Name,Product Base Margin,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
0,18606,Not Specified,0.01,2.88,0.50,2,Janice Fletcher,Regular Air,Corporate,Office Supplies,Labels,Small Box,Avery 49,0.36,Central,Illinois,Addison,60101,2012-05-28,2012-05-30,1.320000,2,5.90,88525
1,20847,High,0.01,2.84,0.93,3,Bonnie Potter,Express Air,Corporate,Office Supplies,Pens & Art Supplies,Wrap Bag,SANFORD Liquid Accent™ Tank-Style Highlighters,0.54,West,Washington,Anacortes,98221,2010-07-07,2010-07-08,4.560000,4,13.01,88522
2,23086,Not Specified,0.03,6.68,6.15,3,Bonnie Potter,Express Air,Corporate,Office Supplies,Paper,Small Box,Xerox 1968,0.37,West,Washington,Anacortes,98221,2011-07-27,2011-07-28,-47.640000,7,49.92,88523
3,23087,Not Specified,0.01,5.68,3.60,3,Bonnie Potter,Regular Air,Corporate,Office Supplies,"Scissors, Rulers and Trimmers",Small Pack,Acme® Preferred Stainless Steel Scissors,0.56,West,Washington,Anacortes,98221,2011-07-27,2011-07-28,-30.510000,7,41.64,88523
4,23088,Not Specified,0.00,205.99,2.50,3,Bonnie Potter,Express Air,Corporate,Technology,Telephones and Communication,Small Box,V70,0.59,West,Washington,Anacortes,98221,2011-07-27,2011-07-27,998.202300,8,1446.67,88523
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9421,20275,Critical,0.06,35.89,14.72,3402,Frederick Cole,Regular Air,Consumer,Office Supplies,Envelopes,Small Box,Jet-Pak Recycled Peel 'N' Seal Padded Mailers,0.40,East,West Virginia,Charleston,25314,2013-05-14,2013-05-15,137.860000,13,447.87,87532
9422,20276,Critical,0.00,3.34,7.49,3402,Frederick Cole,Regular Air,Consumer,Office Supplies,Pens & Art Supplies,Wrap Bag,"Eldon Spacemaker® Box, Quick-Snap Lid, Clear",0.54,East,West Virginia,Charleston,25314,2013-05-14,2013-05-14,-39.070000,3,13.23,87532
9423,24491,Not Specified,0.08,550.98,45.70,3402,Frederick Cole,Delivery Truck,Consumer,Furniture,Tables,Jumbo Box,Chromcraft Bull-Nose Wood Oval Conference Tabl...,0.71,East,West Virginia,Charleston,25314,2013-09-12,2013-09-14,-1225.029097,4,2215.93,87533
9424,25914,High,0.10,105.98,13.99,3403,Tammy Buckley,Express Air,Consumer,Furniture,Office Furnishings,Medium Box,"Tenex 46"" x 60"" Computer Anti-Static Chairmat,...",0.65,West,Wyoming,Cheyenne,82001,2010-02-08,2010-02-11,349.485000,5,506.50,87530
9425,24492,Not Specified,0.09,7.78,2.50,3403,Tammy Buckley,Express Air,Consumer,Office Supplies,Envelopes,Small Box,Staples #10 Colored Envelopes,0.38,West,Wyoming,Cheyenne,82001,2013-09-12,2013-09-14,78.062400,23,172.48,87533

## Select dtypes

In [ ]:
data.dtypes

Row ID                           int64
Order Priority                  object
Discount                       float64
Unit Price                     float64
Shipping Cost                  float64
Customer ID                      int64
Customer Name                   object
Ship Mode                       object
Customer Segment                object
Product Category                object
Product Sub-Category            object
Product Container               object
Product Name                    object
Product Base Margin            float64
Region                          object
State or Province               object
City                            object
Postal Code                      int64
Order Date              datetime64[ns]
Ship Date               datetime64[ns]
Profit                         float64
Quantity ordered new             int64
Sales                          float64
Order ID                         int64
dtype: object

In [ ]:
# Selecting the numerical variables use df.select_dtypes(), include what you want to select as an argument
# you can change int to object and rerun the code.
data.select_dtypes("O") #you can change O with number

,Order Priority,Customer Name,Ship Mode,Customer Segment,Product Category,Product Sub-Category,Product Container,Product Name,Region,State or Province,City
0,Not Specified,Janice Fletcher,Regular Air,Corporate,Office Supplies,Labels,Small Box,Avery 49,Central,Illinois,Addison
1,High,Bonnie Potter,Express Air,Corporate,Office Supplies,Pens & Art Supplies,Wrap Bag,SANFORD Liquid Accent™ Tank-Style Highlighters,West,Washington,Anacortes
2,Not Specified,Bonnie Potter,Express Air,Corporate,Office Supplies,Paper,Small Box,Xerox 1968,West,Washington,Anacortes
3,Not Specified,Bonnie Potter,Regular Air,Corporate,Office Supplies,"Scissors, Rulers and Trimmers",Small Pack,Acme® Preferred Stainless Steel Scissors,West,Washington,Anacortes
4,Not Specified,Bonnie Potter,Express Air,Corporate,Technology,Telephones and Communication,Small Box,V70,West,Washington,Anacortes
...,...,...,...,...,...,...,...,...,...,...,...
9421,Critical,Frederick Cole,Regular Air,Consumer,Office Supplies,Envelopes,Small Box,Jet-Pak Recycled Peel 'N' Seal Padded Mailers,East,West Virginia,Charleston
9422,Critical,Frederick Cole,Regular Air,Consumer,Office Supplies,Pens & Art Supplies,Wrap Bag,"Eldon Spacemaker® Box, Quick-Snap Lid, Clear",East,West Virginia,Charleston
9423,Not Specified,Frederick Cole,Delivery Truck,Consumer,Furniture,Tables,Jumbo Box,Chromcraft Bull-Nose Wood Oval Conference Tabl...,East,West Virginia,Charleston
9424,High,Tammy Buckley,Express Air,Consumer,Furniture,Office Furnishings,Medium Box,"Tenex 46"" x 60"" Computer Anti-Static Chairmat,...",West,Wyoming,Cheyenne
9425,Not Specified,Tammy Buckley,Express Air,Consumer,Office Supplies,Envelopes,Small Box,Staples #10 Colored Envelopes,West,Wyoming,Cheyenne

## Select as series vs dataframe

In [ ]:
#checking the series, use df['Col name']
data["Discount"]

0       0.01
1       0.01
2       0.03
3       0.01
4       0.00
        ...
9421    0.06
9422    0.00
9423    0.08
9424    0.10
9425    0.09
Name: Discount, Length: 9426, dtype: float64

In [ ]:
#making the above as a dataframe , use df[['col name']]
data[["Discount"]]

      Discount
0         0.01
1         0.01
2         0.03
3         0.01
4         0.00
...        ...
9421      0.06
9422      0.00
9423      0.08
9424      0.10
9425      0.09

[9426 rows x 1 columns]

## loc and iloc

We can use loc(variable location), and iloc(index location) to access the variables as well

### iloc

In [ ]:
#checking the dataset
data.head()

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,Product Sub-Category,Product Container,Product Name,Product Base Margin,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
0,18606,Not Specified,0.01,2.88,0.50,2,Janice Fletcher,Regular Air,Corporate,Office Supplies,Labels,Small Box,Avery 49,0.36,Central,Illinois,Addison,60101,2012-05-28,2012-05-30,1.3200,2,5.90,88525
1,20847,High,0.01,2.84,0.93,3,Bonnie Potter,Express Air,Corporate,Office Supplies,Pens & Art Supplies,Wrap Bag,SANFORD Liquid Accent™ Tank-Style Highlighters,0.54,West,Washington,Anacortes,98221,2010-07-07,2010-07-08,4.5600,4,13.01,88522
2,23086,Not Specified,0.03,6.68,6.15,3,Bonnie Potter,Express Air,Corporate,Office Supplies,Paper,Small Box,Xerox 1968,0.37,West,Washington,Anacortes,98221,2011-07-27,2011-07-28,-47.6400,7,49.92,88523
3,23087,Not Specified,0.01,5.68,3.60,3,Bonnie Potter,Regular Air,Corporate,Office Supplies,"Scissors, Rulers and Trimmers",Small Pack,Acme® Preferred Stainless Steel Scissors,0.56,West,Washington,Anacortes,98221,2011-07-27,2011-07-28,-30.5100,7,41.64,88523
4,23088,Not Specified,0.00,205.99,2.50,3,Bonnie Potter,Express Air,Corporate,Technology,Telephones and Communication,Small Box,V70,0.59,West,Washington,Anacortes,98221,2011-07-27,2011-07-27,998.2023,8,1446.67,88523

In [ ]:
# getting the value using iloc e.g df.iloc[1, 1]
data.iloc[0]

Row ID                                18606
Order Priority                Not Specified
Discount                               0.01
Unit Price                             2.88
Shipping Cost                           0.5
Customer ID                               2
Customer Name               Janice Fletcher
Ship Mode                       Regular Air
Customer Segment                  Corporate
Product Category            Office Supplies
Product Sub-Category                 Labels
Product Container                 Small Box
Product Name                       Avery 49
Product Base Margin                    0.36
Region                              Central
State or Province                  Illinois
City                                Addison
Postal Code                           60101
Order Date              2012-05-28 00:00:00
Ship Date               2012-05-30 00:00:00
Profit                                 1.32
Quantity ordered new                      2
Sales                                   5.9
Order ID                              88525
Name: 0, dtype: object

In [ ]:
#get value for row1 and col1
data.iloc[1,1]

'High'

In [ ]:
#slicing e.g df.iloc[:5, :5]
data.iloc[:4,:4]

   Row ID Order Priority  Discount  Unit Price
0   18606  Not Specified      0.01        2.88
1   20847           High      0.01        2.84
2   23086  Not Specified      0.03        6.68
3   23087  Not Specified      0.01        5.68

In [ ]:
#get first 4 rows and column 3 and 4
data.iloc[:4, 2:4]

   Discount  Unit Price
0      0.01        2.88
1      0.01        2.84
2      0.03        6.68
3      0.01        5.68

In [ ]:
#get first 4 rows and column 2 and 7
data.iloc[:4, [2,7]]

   Discount    Ship Mode
0      0.01  Regular Air
1      0.01  Express Air
2      0.03  Express Air
3      0.01  Regular Air

In [ ]:
#get row index 1 and 4 and index 2 and 7
data.iloc[[1,4],[2,7]]

   Discount    Ship Mode
1      0.01  Express Air
4      0.00  Express Air

In [ ]:
#Getting specific row e.g df.iloc[5], we can present our result in dataframe formart as well
data.iloc[5].T()

TypeError: 'Series' object is not callable

In [ ]:
#Checking the index 1 columns e.g df.iloc[:, 1]
data.iloc[:,1]

0       Not Specified
1                High
2       Not Specified
3       Not Specified
4       Not Specified
            ...
9421         Critical
9422         Critical
9423    Not Specified
9424             High
9425    Not Specified
Name: Order Priority, Length: 9426, dtype: object

In [ ]:
#getting index 1 and 2 columns, e.g  df.iloc[:, [1, 2]]
data.iloc[:,[1,2]]

     Order Priority  Discount
0     Not Specified      0.01
1              High      0.01
2     Not Specified      0.03
3     Not Specified      0.01
4     Not Specified      0.00
...             ...       ...
9421       Critical      0.06
9422       Critical      0.00
9423  Not Specified      0.08
9424           High      0.10
9425  Not Specified      0.09

[9426 rows x 2 columns]

Loc

we use loc when we want to select the variable by the name

In [ ]:
data.head()

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,Product Sub-Category,Product Container,Product Name,Product Base Margin,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
0,18606,Not Specified,0.01,2.88,0.50,2,Janice Fletcher,Regular Air,Corporate,Office Supplies,Labels,Small Box,Avery 49,0.36,Central,Illinois,Addison,60101,2012-05-28,2012-05-30,1.3200,2,5.90,88525
1,20847,High,0.01,2.84,0.93,3,Bonnie Potter,Express Air,Corporate,Office Supplies,Pens & Art Supplies,Wrap Bag,SANFORD Liquid Accent™ Tank-Style Highlighters,0.54,West,Washington,Anacortes,98221,2010-07-07,2010-07-08,4.5600,4,13.01,88522
2,23086,Not Specified,0.03,6.68,6.15,3,Bonnie Potter,Express Air,Corporate,Office Supplies,Paper,Small Box,Xerox 1968,0.37,West,Washington,Anacortes,98221,2011-07-27,2011-07-28,-47.6400,7,49.92,88523
3,23087,Not Specified,0.01,5.68,3.60,3,Bonnie Potter,Regular Air,Corporate,Office Supplies,"Scissors, Rulers and Trimmers",Small Pack,Acme® Preferred Stainless Steel Scissors,0.56,West,Washington,Anacortes,98221,2011-07-27,2011-07-28,-30.5100,7,41.64,88523
4,23088,Not Specified,0.00,205.99,2.50,3,Bonnie Potter,Express Air,Corporate,Technology,Telephones and Communication,Small Box,V70,0.59,West,Washington,Anacortes,98221,2011-07-27,2011-07-27,998.2023,8,1446.67,88523

In [ ]:
data.columns

Index(['Row ID', 'Order Priority', 'Discount', 'Unit Price', 'Shipping Cost',
       'Customer ID', 'Customer Name', 'Ship Mode', 'Customer Segment',
       'Product Category', 'Product Sub-Category', 'Product Container',
       'Product Name', 'Product Base Margin', 'Region', 'State or Province',
       'City', 'Postal Code', 'Order Date', 'Ship Date', 'Profit',
       'Quantity ordered new', 'Sales', 'Order ID'],
      dtype='object')

In [ ]:
#subsetting  2 columns df.loc[:, ['col1', 'col2']]
data.loc[4:7,["Discount","Ship Mode"]]

   Discount       Ship Mode
4      0.00     Express Air
5      0.09     Express Air
6      0.08  Delivery Truck
7      0.02  Delivery Truck

In [ ]:
#checking subclass
data["Customer Segment"].unique()

array(['Corporate', 'Home Office', 'Small Business', 'Consumer'],
      dtype=object)

In [ ]:
data.columns

Index(['Row ID', 'Order Priority', 'Discount', 'Unit Price', 'Shipping Cost',
       'Customer ID', 'Customer Name', 'Ship Mode', 'Customer Segment',
       'Product Category', 'Product Sub-Category', 'Product Container',
       'Product Name', 'Product Base Margin', 'Region', 'State or Province',
       'City', 'Postal Code', 'Order Date', 'Ship Date', 'Profit',
       'Quantity ordered new', 'Sales', 'Order ID'],
      dtype='object')

In [ ]:
#converting a column to index
dataind = data.copy(deep=True)
#using index
dataind.index = dataind['Customer Name']
dataind.head()
#another way is setting index
dataind.set_index = dataind["Order Date"]
dataind.head()

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,Product Sub-Category,Product Container,Product Name,Product Base Margin,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
Customer Name,,,,,,,,,,,,,,,,,,,,,,,,
Janice Fletcher,18606,Not Specified,0.01,2.88,0.50,2,Janice Fletcher,Regular Air,Corporate,Office Supplies,Labels,Small Box,Avery 49,0.36,Central,Illinois,Addison,60101,2012-05-28,2012-05-30,1.3200,2,5.90,88525
Bonnie Potter,20847,High,0.01,2.84,0.93,3,Bonnie Potter,Express Air,Corporate,Office Supplies,Pens & Art Supplies,Wrap Bag,SANFORD Liquid Accent™ Tank-Style Highlighters,0.54,West,Washington,Anacortes,98221,2010-07-07,2010-07-08,4.5600,4,13.01,88522
Bonnie Potter,23086,Not Specified,0.03,6.68,6.15,3,Bonnie Potter,Express Air,Corporate,Office Supplies,Paper,Small Box,Xerox 1968,0.37,West,Washington,Anacortes,98221,2011-07-27,2011-07-28,-47.6400,7,49.92,88523
Bonnie Potter,23087,Not Specified,0.01,5.68,3.60,3,Bonnie Potter,Regular Air,Corporate,Office Supplies,"Scissors, Rulers and Trimmers",Small Pack,Acme® Preferred Stainless Steel Scissors,0.56,West,Washington,Anacortes,98221,2011-07-27,2011-07-28,-30.5100,7,41.64,88523
Bonnie Potter,23088,Not Specified,0.00,205.99,2.50,3,Bonnie Potter,Express Air,Corporate,Technology,Telephones and Communication,Small Box,V70,0.59,West,Washington,Anacortes,98221,2011-07-27,2011-07-27,998.2023,8,1446.67,88523

#### loc filter expressions

we can use loc filter to get specific records

In [ ]:
data_sma = data[data['Customer Segment'] == 'Small Business']
data_sma.head()

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,Product Sub-Category,Product Container,Product Name,Product Base Margin,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
19,24844,Medium,0.09,78.69,19.99,14,Gwendolyn F Tyson,Regular Air,Small Business,Furniture,Office Furnishings,Small Box,Howard Miller 12-3/4 Diameter Accuwave DS ™ Wa...,0.43,Central,Minnesota,Prior Lake,55372,2010-05-12,2010-05-14,803.4705,16,1164.45,86838
20,24846,Medium,0.08,3.28,2.31,14,Gwendolyn F Tyson,Regular Air,Small Business,Office Supplies,Pens & Art Supplies,Wrap Bag,Newell 321,0.56,Central,Minnesota,Prior Lake,55372,2010-05-12,2010-05-13,-24.0300,7,22.23,86838
21,24847,Medium,0.05,3.28,4.20,14,Gwendolyn F Tyson,Regular Air,Small Business,Office Supplies,Pens & Art Supplies,Wrap Bag,Newell 351,0.56,Central,Minnesota,Prior Lake,55372,2010-05-12,2010-05-13,-37.0300,4,13.99,86838
22,24848,Medium,0.05,3.58,1.63,14,Gwendolyn F Tyson,Regular Air,Small Business,Office Supplies,Rubber Bands,Wrap Bag,"OIC Colored Binder Clips, Assorted Sizes",0.36,Central,Minnesota,Prior Lake,55372,2010-05-12,2010-05-13,-0.7100,4,14.26,86838
23,24845,Medium,0.01,6.48,7.86,14,Gwendolyn F Tyson,Regular Air,Small Business,Office Supplies,Paper,Small Box,Xerox 213,0.37,Central,Minnesota,Prior Lake,55372,2013-05-12,2013-05-13,-44.5400,4,29.55,86845

In [ ]:
data_sma["Customer Segment"].unique()

array(['Small Business'], dtype=object)

In [ ]:
#Get the records of a specific value e.g  df.loc[df['Region'] == 'West']
data.loc[data['Customer Segment'] == 'Small Business']

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,Product Sub-Category,Product Container,Product Name,Product Base Margin,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
19,24844,Medium,0.09,78.69,19.99,14,Gwendolyn F Tyson,Regular Air,Small Business,Furniture,Office Furnishings,Small Box,Howard Miller 12-3/4 Diameter Accuwave DS ™ Wa...,0.43,Central,Minnesota,Prior Lake,55372,2010-05-12,2010-05-14,803.47050,16,1164.45,86838
20,24846,Medium,0.08,3.28,2.31,14,Gwendolyn F Tyson,Regular Air,Small Business,Office Supplies,Pens & Art Supplies,Wrap Bag,Newell 321,0.56,Central,Minnesota,Prior Lake,55372,2010-05-12,2010-05-13,-24.03000,7,22.23,86838
21,24847,Medium,0.05,3.28,4.20,14,Gwendolyn F Tyson,Regular Air,Small Business,Office Supplies,Pens & Art Supplies,Wrap Bag,Newell 351,0.56,Central,Minnesota,Prior Lake,55372,2010-05-12,2010-05-13,-37.03000,4,13.99,86838
22,24848,Medium,0.05,3.58,1.63,14,Gwendolyn F Tyson,Regular Air,Small Business,Office Supplies,Rubber Bands,Wrap Bag,"OIC Colored Binder Clips, Assorted Sizes",0.36,Central,Minnesota,Prior Lake,55372,2010-05-12,2010-05-13,-0.71000,4,14.26,86838
23,24845,Medium,0.01,6.48,7.86,14,Gwendolyn F Tyson,Regular Air,Small Business,Office Supplies,Paper,Small Box,Xerox 213,0.37,Central,Minnesota,Prior Lake,55372,2013-05-12,2013-05-13,-44.54000,4,29.55,86845
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9410,26073,Critical,0.05,59.78,10.29,3399,Marvin Reid,Regular Air,Small Business,Office Supplies,Binders and Binder Accessories,Small Box,GBC Recycled Regency Composition Covers,0.39,Central,Illinois,Des Plaines,60016,2013-11-11,2013-11-13,1176.91230,29,1705.67,87551
9411,26074,Critical,0.05,4.13,0.50,3399,Marvin Reid,Regular Air,Small Business,Office Supplies,Labels,Small Box,Avery 506,0.39,Central,Illinois,Des Plaines,60016,2013-11-11,2013-11-13,117.26550,40,169.95,87551
9412,26075,Critical,0.01,30.98,17.08,3399,Marvin Reid,Regular Air,Small Business,Office Supplies,Paper,Small Box,Xerox 197,0.40,Central,Illinois,Des Plaines,60016,2013-11-11,2013-11-13,3.90688,11,373.27,87551
9413,24911,Medium,0.10,9.38,4.93,3400,Florence Gold,Express Air,Small Business,Furniture,Office Furnishings,Small Box,Eldon Expressions Punched Metal & Wood Desk Ac...,0.57,East,West Virginia,Fairmont,26554,2010-10-04,2010-10-04,-24.71040,15,135.78,87537
9419,24912,Medium,0.05,35.99,1.25,3400,Florence Gold,Regular Air,Small Business,Technology,Telephones and Communication,Small Pack,Accessory23,0.36,East,West Virginia,Fairmont,26554,2013-10-04,2013-10-05,411.48150,19,596.35,87549

In [ ]:
#subset data getting furniture
data_fun =

In [ ]:
#we can use loc to get records of more than one specific variables
#df.loc[(df['Product Category'] == 'Furniture') & (df['Order Date'] == '2010-07-07')]
data.loc[(data['Product Category'] == 'Furniture') & (data['Order Date'] == '2010-07-07')]

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,Product Sub-Category,Product Container,Product Name,Product Base Margin,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
1639,25539,Critical,0.03,14.20,5.30,619,Howard Rogers,Regular Air,Consumer,Furniture,Office Furnishings,Wrap Bag,Coloredge Poster Frame,0.46,Central,Michigan,Southgate,48195,2010-07-07,2010-07-08,107.0200,14,205.98,88196
4805,19419,Low,0.03,5.08,2.03,1781,Jackie Capps,Regular Air,Home Office,Furniture,Office Furnishings,Wrap Bag,"Master Caster Door Stop, Brown",0.51,West,California,San Carlos,94070,2010-07-07,2010-07-12,15.1524,4,21.96,89858
8467,19739,Medium,0.00,137.48,32.18,3076,Peter Hardy,Delivery Truck,Small Business,Furniture,Bookcases,Jumbo Box,O'Sullivan Cherrywood Estates Traditional Barr...,0.78,East,Ohio,Stow,44224,2010-07-07,2010-07-08,-203.2700,2,296.75,88241
8492,1739,Medium,0.00,137.48,32.18,3079,Andrew Levine,Delivery Truck,Small Business,Furniture,Bookcases,Jumbo Box,O'Sullivan Cherrywood Estates Traditional Barr...,0.78,East,Pennsylvania,Philadelphia,19112,2010-07-07,2010-07-08,-203.2700,10,1483.76,12480

In [ ]:
#we can use tilde(~) to get the records of those not represented in the code
#df.loc[~((df['Product Category'] == 'Furniture') & (df['Order Date'] == '2010-07-07'))]
data.loc[~((data['Product Category'] == 'Furniture') & (data['Order Date'] == '2010-07-07'))]

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,Product Sub-Category,Product Container,Product Name,Product Base Margin,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
0,18606,Not Specified,0.01,2.88,0.50,2,Janice Fletcher,Regular Air,Corporate,Office Supplies,Labels,Small Box,Avery 49,0.36,Central,Illinois,Addison,60101,2012-05-28,2012-05-30,1.320000,2,5.90,88525
1,20847,High,0.01,2.84,0.93,3,Bonnie Potter,Express Air,Corporate,Office Supplies,Pens & Art Supplies,Wrap Bag,SANFORD Liquid Accent™ Tank-Style Highlighters,0.54,West,Washington,Anacortes,98221,2010-07-07,2010-07-08,4.560000,4,13.01,88522
2,23086,Not Specified,0.03,6.68,6.15,3,Bonnie Potter,Express Air,Corporate,Office Supplies,Paper,Small Box,Xerox 1968,0.37,West,Washington,Anacortes,98221,2011-07-27,2011-07-28,-47.640000,7,49.92,88523
3,23087,Not Specified,0.01,5.68,3.60,3,Bonnie Potter,Regular Air,Corporate,Office Supplies,"Scissors, Rulers and Trimmers",Small Pack,Acme® Preferred Stainless Steel Scissors,0.56,West,Washington,Anacortes,98221,2011-07-27,2011-07-28,-30.510000,7,41.64,88523
4,23088,Not Specified,0.00,205.99,2.50,3,Bonnie Potter,Express Air,Corporate,Technology,Telephones and Communication,Small Box,V70,0.59,West,Washington,Anacortes,98221,2011-07-27,2011-07-27,998.202300,8,1446.67,88523
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9421,20275,Critical,0.06,35.89,14.72,3402,Frederick Cole,Regular Air,Consumer,Office Supplies,Envelopes,Small Box,Jet-Pak Recycled Peel 'N' Seal Padded Mailers,0.40,East,West Virginia,Charleston,25314,2013-05-14,2013-05-15,137.860000,13,447.87,87532
9422,20276,Critical,0.00,3.34,7.49,3402,Frederick Cole,Regular Air,Consumer,Office Supplies,Pens & Art Supplies,Wrap Bag,"Eldon Spacemaker® Box, Quick-Snap Lid, Clear",0.54,East,West Virginia,Charleston,25314,2013-05-14,2013-05-14,-39.070000,3,13.23,87532
9423,24491,Not Specified,0.08,550.98,45.70,3402,Frederick Cole,Delivery Truck,Consumer,Furniture,Tables,Jumbo Box,Chromcraft Bull-Nose Wood Oval Conference Tabl...,0.71,East,West Virginia,Charleston,25314,2013-09-12,2013-09-14,-1225.029097,4,2215.93,87533
9424,25914,High,0.10,105.98,13.99,3403,Tammy Buckley,Express Air,Consumer,Furniture,Office Furnishings,Medium Box,"Tenex 46"" x 60"" Computer Anti-Static Chairmat,...",0.65,West,Wyoming,Cheyenne,82001,2010-02-08,2010-02-11,349.485000,5,506.50,87530
9425,24492,Not Specified,0.09,7.78,2.50,3403,Tammy Buckley,Express Air,Consumer,Office Supplies,Envelopes,Small Box,Staples #10 Colored Envelopes,0.38,West,Wyoming,Cheyenne,82001,2013-09-12,2013-09-14,78.062400,23,172.48,87533

## query

Query method is another way of getting specific records

In [ ]:
?data.query

In [ ]:
#getting specific records
data.query('Sales < 300 and Region=="West"')

In [ ]:
#Another different way of using query method
#min_sale =600
#data.query(Sales > @min_sale and (Region == "West")')

In [ ]:
from IPython.display import display, HTML
df1 = data.query("Region=='West'")
df1.head()

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,...,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
1,20847,High,0.01,2.84,0.93,3,Bonnie Potter,Express Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221,2010-07-07,2010-07-08,4.5600,4,13.01,88522
2,23086,Not Specified,0.03,6.68,6.15,3,Bonnie Potter,Express Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221,2011-07-27,2011-07-28,-47.6400,7,49.92,88523
3,23087,Not Specified,0.01,5.68,3.60,3,Bonnie Potter,Regular Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221,2011-07-27,2011-07-28,-30.5100,7,41.64,88523
4,23088,Not Specified,0.00,205.99,2.50,3,Bonnie Potter,Express Air,Corporate,Technology,...,West,Washington,Anacortes,98221,2011-07-27,2011-07-27,998.2023,8,1446.67,88523
5,23597,Medium,0.09,55.48,14.30,3,Bonnie Potter,Express Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221,2011-11-09,2011-11-11,1388.0523,37,2011.67,88524