<a href="https://colab.research.google.com/github/joyangelai/Colabs/blob/main/cohort2_pandas2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas

In [ ]:
#Import pandas and numpy
import pandas as pd # for data manipulation and analysis
import numpy as np # used for mathematical computation # built on top of pandas

Data stractures used in pandas
1. pandas series
2. pandas data Frame

In [ ]:
#Create a  num and str list and convert it to a series
a = ["car", "boat", "bike"] #list

series1 = pd.Series(a)
print(series1)
print(type(series1))

0     car
1    boat
2    bike
dtype: object
<class 'pandas.core.series.Series'>

In [ ]:
#create a list and convert it to a dataframe
a = [("car", 100), ("boat", 70), ("bike", 40)]

df = pd.DataFrame(a, columns=("item", "price"))
print(df)
type(df)

   item  price
0   car    100
1  boat     70
2  bike     40

pandas.core.frame.DataFrame

In [ ]:
df.to_csv('df.csv', index=None)

In [ ]:
#load

In [ ]:
#save the dataframe to csv file
df.to_csv("item.csv", index =None)

In [ ]:
#load the saved item dataset
df2 = pd.read_csv("item.csv")
df2

   item  price
0   car    100
1  boat     70
2  bike     40

In [ ]:
#prove that the dataframe is made up of more than one series

df_price = df['price']
type(df_price)

pandas.core.series.Series

## Reading from files

In [ ]:
#Loading the dataset #excel dataset
dataDf =pd.read_excel('Sample_Superstore.xlsx')

dataDf

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,...,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
0,18606,Not Specified,0.01,2.88,0.50,2,Janice Fletcher,Regular Air,Corporate,Office Supplies,...,Central,Illinois,Addison,60101,2012-05-28,2012-05-30,1.320000,2,5.90,88525
1,20847,High,0.01,2.84,0.93,3,Bonnie Potter,Express Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221,2010-07-07,2010-07-08,4.560000,4,13.01,88522
2,23086,Not Specified,0.03,6.68,6.15,3,Bonnie Potter,Express Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221,2011-07-27,2011-07-28,-47.640000,7,49.92,88523
3,23087,Not Specified,0.01,5.68,3.60,3,Bonnie Potter,Regular Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221,2011-07-27,2011-07-28,-30.510000,7,41.64,88523
4,23088,Not Specified,0.00,205.99,2.50,3,Bonnie Potter,Express Air,Corporate,Technology,...,West,Washington,Anacortes,98221,2011-07-27,2011-07-27,998.202300,8,1446.67,88523
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9421,20275,Critical,0.06,35.89,14.72,3402,Frederick Cole,Regular Air,Consumer,Office Supplies,...,East,West Virginia,Charleston,25314,2013-05-14,2013-05-15,137.860000,13,447.87,87532
9422,20276,Critical,0.00,3.34,7.49,3402,Frederick Cole,Regular Air,Consumer,Office Supplies,...,East,West Virginia,Charleston,25314,2013-05-14,2013-05-14,-39.070000,3,13.23,87532
9423,24491,Not Specified,0.08,550.98,45.70,3402,Frederick Cole,Delivery Truck,Consumer,Furniture,...,East,West Virginia,Charleston,25314,2013-09-12,2013-09-14,-1225.029097,4,2215.93,87533
9424,25914,High,0.10,105.98,13.99,3403,Tammy Buckley,Express Air,Consumer,Furniture,...,West,Wyoming,Cheyenne,82001,2010-02-08,2010-02-11,349.485000,5,506.50,87530
9425,24492,Not Specified,0.09,7.78,2.50,3403,Tammy Buckley,Express Air,Consumer,Office Supplies,...,West,Wyoming,Cheyenne,82001,2013-09-12,2013-09-14,78.062400,23,172.48,87533

## Writing to files

In [ ]:
#saving the file to csv # use to_csv() and set index = False
data.to_csv("superstore.csv", index=None)

In [ ]:
datasv = pd.read_csv("superstore.csv")
datasv

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,...,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
0,18606,Not Specified,0.01,2.88,0.50,2,Janice Fletcher,Regular Air,Corporate,Office Supplies,...,Central,Illinois,Addison,60101,2012-05-28,2012-05-30,1.320000,2,5.90,88525
1,20847,High,0.01,2.84,0.93,3,Bonnie Potter,Express Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221,2010-07-07,2010-07-08,4.560000,4,13.01,88522
2,23086,Not Specified,0.03,6.68,6.15,3,Bonnie Potter,Express Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221,2011-07-27,2011-07-28,-47.640000,7,49.92,88523
3,23087,Not Specified,0.01,5.68,3.60,3,Bonnie Potter,Regular Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221,2011-07-27,2011-07-28,-30.510000,7,41.64,88523
4,23088,Not Specified,0.00,205.99,2.50,3,Bonnie Potter,Express Air,Corporate,Technology,...,West,Washington,Anacortes,98221,2011-07-27,2011-07-27,998.202300,8,1446.67,88523
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9421,20275,Critical,0.06,35.89,14.72,3402,Frederick Cole,Regular Air,Consumer,Office Supplies,...,East,West Virginia,Charleston,25314,2013-05-14,2013-05-15,137.860000,13,447.87,87532
9422,20276,Critical,0.00,3.34,7.49,3402,Frederick Cole,Regular Air,Consumer,Office Supplies,...,East,West Virginia,Charleston,25314,2013-05-14,2013-05-14,-39.070000,3,13.23,87532
9423,24491,Not Specified,0.08,550.98,45.70,3402,Frederick Cole,Delivery Truck,Consumer,Furniture,...,East,West Virginia,Charleston,25314,2013-09-12,2013-09-14,-1225.029097,4,2215.93,87533
9424,25914,High,0.10,105.98,13.99,3403,Tammy Buckley,Express Air,Consumer,Furniture,...,West,Wyoming,Cheyenne,82001,2010-02-08,2010-02-11,349.485000,5,506.50,87530
9425,24492,Not Specified,0.09,7.78,2.50,3403,Tammy Buckley,Express Air,Consumer,Office Supplies,...,West,Wyoming,Cheyenne,82001,2013-09-12,2013-09-14,78.062400,23,172.48,87533

## Dataframe basics

In [ ]:
#setting the default data view # pd.set_option("display.max_columns", 500)
pd.set_option("display.max_column", 200)

In [ ]:
#display the data
dataDf

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,Product Sub-Category,Product Container,Product Name,Product Base Margin,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
0,18606,Not Specified,0.01,2.88,0.50,2,Janice Fletcher,Regular Air,Corporate,Office Supplies,Labels,Small Box,Avery 49,0.36,Central,Illinois,Addison,60101,2012-05-28,2012-05-30,1.320000,2,5.90,88525
1,20847,High,0.01,2.84,0.93,3,Bonnie Potter,Express Air,Corporate,Office Supplies,Pens & Art Supplies,Wrap Bag,SANFORD Liquid Accent™ Tank-Style Highlighters,0.54,West,Washington,Anacortes,98221,2010-07-07,2010-07-08,4.560000,4,13.01,88522
2,23086,Not Specified,0.03,6.68,6.15,3,Bonnie Potter,Express Air,Corporate,Office Supplies,Paper,Small Box,Xerox 1968,0.37,West,Washington,Anacortes,98221,2011-07-27,2011-07-28,-47.640000,7,49.92,88523
3,23087,Not Specified,0.01,5.68,3.60,3,Bonnie Potter,Regular Air,Corporate,Office Supplies,"Scissors, Rulers and Trimmers",Small Pack,Acme® Preferred Stainless Steel Scissors,0.56,West,Washington,Anacortes,98221,2011-07-27,2011-07-28,-30.510000,7,41.64,88523
4,23088,Not Specified,0.00,205.99,2.50,3,Bonnie Potter,Express Air,Corporate,Technology,Telephones and Communication,Small Box,V70,0.59,West,Washington,Anacortes,98221,2011-07-27,2011-07-27,998.202300,8,1446.67,88523
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9421,20275,Critical,0.06,35.89,14.72,3402,Frederick Cole,Regular Air,Consumer,Office Supplies,Envelopes,Small Box,Jet-Pak Recycled Peel 'N' Seal Padded Mailers,0.40,East,West Virginia,Charleston,25314,2013-05-14,2013-05-15,137.860000,13,447.87,87532
9422,20276,Critical,0.00,3.34,7.49,3402,Frederick Cole,Regular Air,Consumer,Office Supplies,Pens & Art Supplies,Wrap Bag,"Eldon Spacemaker® Box, Quick-Snap Lid, Clear",0.54,East,West Virginia,Charleston,25314,2013-05-14,2013-05-14,-39.070000,3,13.23,87532
9423,24491,Not Specified,0.08,550.98,45.70,3402,Frederick Cole,Delivery Truck,Consumer,Furniture,Tables,Jumbo Box,Chromcraft Bull-Nose Wood Oval Conference Tabl...,0.71,East,West Virginia,Charleston,25314,2013-09-12,2013-09-14,-1225.029097,4,2215.93,87533
9424,25914,High,0.10,105.98,13.99,3403,Tammy Buckley,Express Air,Consumer,Furniture,Office Furnishings,Medium Box,"Tenex 46"" x 60"" Computer Anti-Static Chairmat,...",0.65,West,Wyoming,Cheyenne,82001,2010-02-08,2010-02-11,349.485000,5,506.50,87530
9425,24492,Not Specified,0.09,7.78,2.50,3403,Tammy Buckley,Express Air,Consumer,Office Supplies,Envelopes,Small Box,Staples #10 Colored Envelopes,0.38,West,Wyoming,Cheyenne,82001,2013-09-12,2013-09-14,78.062400,23,172.48,87533

### Initial Exploratory Data analysis (IDA)

In [ ]:
#checking a few top rows
dataDf.head()

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,Product Sub-Category,Product Container,Product Name,Product Base Margin,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
0,18606,Not Specified,0.01,2.88,0.50,2,Janice Fletcher,Regular Air,Corporate,Office Supplies,Labels,Small Box,Avery 49,0.36,Central,Illinois,Addison,60101,2012-05-28,2012-05-30,1.3200,2,5.90,88525
1,20847,High,0.01,2.84,0.93,3,Bonnie Potter,Express Air,Corporate,Office Supplies,Pens & Art Supplies,Wrap Bag,SANFORD Liquid Accent™ Tank-Style Highlighters,0.54,West,Washington,Anacortes,98221,2010-07-07,2010-07-08,4.5600,4,13.01,88522
2,23086,Not Specified,0.03,6.68,6.15,3,Bonnie Potter,Express Air,Corporate,Office Supplies,Paper,Small Box,Xerox 1968,0.37,West,Washington,Anacortes,98221,2011-07-27,2011-07-28,-47.6400,7,49.92,88523
3,23087,Not Specified,0.01,5.68,3.60,3,Bonnie Potter,Regular Air,Corporate,Office Supplies,"Scissors, Rulers and Trimmers",Small Pack,Acme® Preferred Stainless Steel Scissors,0.56,West,Washington,Anacortes,98221,2011-07-27,2011-07-28,-30.5100,7,41.64,88523
4,23088,Not Specified,0.00,205.99,2.50,3,Bonnie Potter,Express Air,Corporate,Technology,Telephones and Communication,Small Box,V70,0.59,West,Washington,Anacortes,98221,2011-07-27,2011-07-27,998.2023,8,1446.67,88523

In [ ]:
#Bottom 5 rows
dataDf.tail()

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,Product Sub-Category,Product Container,Product Name,Product Base Margin,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
9421,20275,Critical,0.06,35.89,14.72,3402,Frederick Cole,Regular Air,Consumer,Office Supplies,Envelopes,Small Box,Jet-Pak Recycled Peel 'N' Seal Padded Mailers,0.40,East,West Virginia,Charleston,25314,2013-05-14,2013-05-15,137.860000,13,447.87,87532
9422,20276,Critical,0.00,3.34,7.49,3402,Frederick Cole,Regular Air,Consumer,Office Supplies,Pens & Art Supplies,Wrap Bag,"Eldon Spacemaker® Box, Quick-Snap Lid, Clear",0.54,East,West Virginia,Charleston,25314,2013-05-14,2013-05-14,-39.070000,3,13.23,87532
9423,24491,Not Specified,0.08,550.98,45.70,3402,Frederick Cole,Delivery Truck,Consumer,Furniture,Tables,Jumbo Box,Chromcraft Bull-Nose Wood Oval Conference Tabl...,0.71,East,West Virginia,Charleston,25314,2013-09-12,2013-09-14,-1225.029097,4,2215.93,87533
9424,25914,High,0.10,105.98,13.99,3403,Tammy Buckley,Express Air,Consumer,Furniture,Office Furnishings,Medium Box,"Tenex 46"" x 60"" Computer Anti-Static Chairmat,...",0.65,West,Wyoming,Cheyenne,82001,2010-02-08,2010-02-11,349.485000,5,506.50,87530
9425,24492,Not Specified,0.09,7.78,2.50,3403,Tammy Buckley,Express Air,Consumer,Office Supplies,Envelopes,Small Box,Staples #10 Colored Envelopes,0.38,West,Wyoming,Cheyenne,82001,2013-09-12,2013-09-14,78.062400,23,172.48,87533

In [ ]:
#Displaying the top 3 rows #
dataDf.head(3)

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,Product Sub-Category,Product Container,Product Name,Product Base Margin,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
0,18606,Not Specified,0.01,2.88,0.50,2,Janice Fletcher,Regular Air,Corporate,Office Supplies,Labels,Small Box,Avery 49,0.36,Central,Illinois,Addison,60101,2012-05-28,2012-05-30,1.32,2,5.90,88525
1,20847,High,0.01,2.84,0.93,3,Bonnie Potter,Express Air,Corporate,Office Supplies,Pens & Art Supplies,Wrap Bag,SANFORD Liquid Accent™ Tank-Style Highlighters,0.54,West,Washington,Anacortes,98221,2010-07-07,2010-07-08,4.56,4,13.01,88522
2,23086,Not Specified,0.03,6.68,6.15,3,Bonnie Potter,Express Air,Corporate,Office Supplies,Paper,Small Box,Xerox 1968,0.37,West,Washington,Anacortes,98221,2011-07-27,2011-07-28,-47.64,7,49.92,88523

In [ ]:
#Displaying the last 3 rows #
dataDf.tail(3)

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,Product Sub-Category,Product Container,Product Name,Product Base Margin,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
9423,24491,Not Specified,0.08,550.98,45.70,3402,Frederick Cole,Delivery Truck,Consumer,Furniture,Tables,Jumbo Box,Chromcraft Bull-Nose Wood Oval Conference Tabl...,0.71,East,West Virginia,Charleston,25314,2013-09-12,2013-09-14,-1225.029097,4,2215.93,87533
9424,25914,High,0.10,105.98,13.99,3403,Tammy Buckley,Express Air,Consumer,Furniture,Office Furnishings,Medium Box,"Tenex 46"" x 60"" Computer Anti-Static Chairmat,...",0.65,West,Wyoming,Cheyenne,82001,2010-02-08,2010-02-11,349.485000,5,506.50,87530
9425,24492,Not Specified,0.09,7.78,2.50,3403,Tammy Buckley,Express Air,Consumer,Office Supplies,Envelopes,Small Box,Staples #10 Colored Envelopes,0.38,West,Wyoming,Cheyenne,82001,2013-09-12,2013-09-14,78.062400,23,172.48,87533

In [ ]:
#Displaying 3 random rows #use sample()
dataDf.sample(4)

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,Product Sub-Category,Product Container,Product Name,Product Base Margin,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
8101,25053,Medium,0.03,20.95,4.00,2951,Jordan Womble,Regular Air,Corporate,Technology,Computer Peripherals,Small Box,"Fellowes Basic 104-Key Keyboard, Platinum",0.60,Central,Kansas,Hays,67601,2013-08-15,2013-08-17,53.63128,11,241.19,91402
3113,18831,Low,0.03,7.96,4.95,1189,Dwight Stephenson,Regular Air,Consumer,Furniture,Office Furnishings,Small Box,Staples Plastic Wall Frames,0.41,West,California,Huntington Beach,92646,2010-06-17,2010-06-19,24.26040,4,35.16,87584
533,23148,Critical,0.10,65.99,8.99,205,Priscilla Owen,Regular Air,Corporate,Technology,Telephones and Communication,Small Box,Talkabout T8367,0.56,Central,Texas,Deer Park,77536,2012-08-30,2012-09-02,184.74840,14,745.91,89239
2330,7038,Medium,0.05,6.48,7.37,894,Gail Rankin Cole,Express Air,Corporate,Office Supplies,Paper,Small Box,Xerox 210,0.37,East,District of Columbia,Washington,20024,2011-08-18,2011-08-19,-47.67000,25,182.21,50246

In [ ]:
#checking the columns # use columns attribute
dataDf.columns

Index(['Row ID', 'Order Priority', 'Discount', 'Unit Price', 'Shipping Cost',
       'Customer ID', 'Customer Name', 'Ship Mode', 'Customer Segment',
       'Product Category', 'Product Sub-Category', 'Product Container',
       'Product Name', 'Product Base Margin', 'Region', 'State or Province',
       'City', 'Postal Code', 'Order Date', 'Ship Date', 'Profit',
       'Quantity ordered new', 'Sales', 'Order ID'],
      dtype='object')

In [ ]:
#using list comprehesion
#Using list comprehnsion e.g [c for c in df.columns]
[c for c in dataDf.columns]

['Row ID',
 'Order Priority',
 'Discount',
 'Unit Price',
 'Shipping Cost',
 'Customer ID',
 'Customer Name',
 'Ship Mode',
 'Customer Segment',
 'Product Category',
 'Product Sub-Category',
 'Product Container',
 'Product Name',
 'Product Base Margin',
 'Region',
 'State or Province',
 'City',
 'Postal Code',
 'Order Date',
 'Ship Date',
 'Profit',
 'Quantity ordered new',
 'Sales',
 'Order ID']

In [ ]:
#checking the index # use df.index
dataDf.index

RangeIndex(start=0, stop=9426, step=1)

In [ ]:
#check the shape
dataDf.shape

(9426, 24)

In [ ]:
#getting records
len(dataDf)

9426

In [ ]:
#check the shape
print(f" This dataset has {dataDf.shape[0]} records and {dataDf.shape[1]} columns")

 This dataset has 9426 records and 24 columns

## Dataframe summary

In [ ]:
#Checking the data Summary # use info(), we can also use info(verbose=False)
dataDf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9426 entries, 0 to 9425
Data columns (total 24 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Row ID                9426 non-null   int64
 1   Order Priority        9426 non-null   object
 2   Discount              9426 non-null   float64
 3   Unit Price            9426 non-null   float64
 4   Shipping Cost         9426 non-null   float64
 5   Customer ID           9426 non-null   int64
 6   Customer Name         9426 non-null   object
 7   Ship Mode             9426 non-null   object
 8   Customer Segment      9426 non-null   object
 9   Product Category      9426 non-null   object
 10  Product Sub-Category  9426 non-null   object
 11  Product Container     9426 non-null   object
 12  Product Name          9426 non-null   object
 13  Product Base Margin   9354 non-null   float64
 14  Region                9426 non-null   object
 15  State or Province     9426 non-null   object
 16  City                  9426 non-null   object
 17  Postal Code           9426 non-null   int64
 18  Order Date            9426 non-null   datetime64[ns]
 19  Ship Date             9426 non-null   datetime64[ns]
 20  Profit                9426 non-null   float64
 21  Quantity ordered new  9426 non-null   int64
 22  Sales                 9426 non-null   float64
 23  Order ID              9426 non-null   int64
dtypes: datetime64[ns](2), float64(6), int64(5), object(11)
memory usage: 1.7+ MB

In [ ]:
# incoperating verbose argument
dataDf.info(verbose=False)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9426 entries, 0 to 9425
Columns: 24 entries, Row ID to Order ID
dtypes: datetime64[ns](2), float64(6), int64(5), object(11)
memory usage: 1.7+ MB

In [ ]:
#Checking concise Descriptive statistics for numerical variables# use .describe
dataDf.describe().T

,count,mean,min,25%,50%,75%,max,std
Row ID,9426.0,20241.015277,2.0,19330.25,21686.5,24042.75,26399.0,6101.890965
Discount,9426.0,0.049628,0.0,0.02,0.05,0.08,0.25,0.031798
Unit Price,9426.0,88.303686,0.99,6.48,20.99,85.99,6783.02,281.540982
Shipping Cost,9426.0,12.795142,0.49,3.1925,6.05,13.99,164.73,17.181203
Customer ID,9426.0,1738.422236,2.0,898.0,1750.0,2578.75,3403.0,979.167197
Product Base Margin,9354.0,0.512189,0.35,0.38,0.52,0.59,0.85,0.135229
Postal Code,9426.0,52446.327286,1001.0,29406.0,52302.0,78516.0,99362.0,29374.597802
Order Date,9426,2012-03-05 18:33:59.465308672,2010-01-01 00:00:00,2011-03-07 06:00:00,2012-04-08 00:00:00,2013-03-26 00:00:00,2013-12-31 00:00:00,NaN
Ship Date,9426,2012-03-07 19:16:18.485041408,2010-01-02 00:00:00,2011-03-09 00:00:00,2012-04-09 00:00:00,2013-03-28 00:00:00,2014-01-17 00:00:00,NaN
Profit,9426.0,139.23641,-16476.838,-74.017375,2.5676,140.24385,16332.414,998.486483
Quantity ordered new,9426.0,13.79843,1.0,5.0,10.0,17.0,170.0,15.107688
Sales,9426.0,949.706272,1.32,61.2825,203.455,776.4025,100119.16,2598.019818
Order ID,9426.0,82318.489073,6.0,86737.25,88344.5,89987.75,91591.0,19149.448857

In [ ]:
#summary stst for numerical values
dataDf.describe(include = (["float", "int"]))

,Row ID,Discount,Unit Price,Shipping Cost,Customer ID,Product Base Margin,Postal Code,Profit,Quantity ordered new,Sales,Order ID
count,9426.000000,9426.000000,9426.000000,9426.000000,9426.000000,9354.000000,9426.000000,9426.000000,9426.000000,9426.000000,9426.000000
mean,20241.015277,0.049628,88.303686,12.795142,1738.422236,0.512189,52446.327286,139.236410,13.798430,949.706272,82318.489073
std,6101.890965,0.031798,281.540982,17.181203,979.167197,0.135229,29374.597802,998.486483,15.107688,2598.019818,19149.448857
min,2.000000,0.000000,0.990000,0.490000,2.000000,0.350000,1001.000000,-16476.838000,1.000000,1.320000,6.000000
25%,19330.250000,0.020000,6.480000,3.192500,898.000000,0.380000,29406.000000,-74.017375,5.000000,61.282500,86737.250000
50%,21686.500000,0.050000,20.990000,6.050000,1750.000000,0.520000,52302.000000,2.567600,10.000000,203.455000,88344.500000
75%,24042.750000,0.080000,85.990000,13.990000,2578.750000,0.590000,78516.000000,140.243850,17.000000,776.402500,89987.750000
max,26399.000000,0.250000,6783.020000,164.730000,3403.000000,0.850000,99362.000000,16332.414000,170.000000,100119.160000,91591.000000

In [ ]:
#Checking concise Descriptive statistics for categorical variables# use coln.describe()
dataDf.describe(include = 'O').T  # you can use object

,count,unique,top,freq
Order Priority,9426,6,High,1970
Customer Name,9426,2703,Louis Parrish,27
Ship Mode,9426,3,Regular Air,7036
Customer Segment,9426,4,Corporate,3375
Product Category,9426,3,Office Supplies,5181
Product Sub-Category,9426,17,Paper,1379
Product Container,9426,7,Small Box,4887
Product Name,9426,1263,"Global High-Back Leather Tilter, Burgundy",27
Region,9426,4,Central,2899
State or Province,9426,49,California,1021
City,9426,1424,New York City,202

In [ ]:
#another way of checking cat summary stst
dataDf.describe(include = 'object')  # you can use object

,Order Priority,Customer Name,Ship Mode,Customer Segment,Product Category,Product Sub-Category,Product Container,Product Name,Region,State or Province,City
count,9426,9426,9426,9426,9426,9426,9426,9426,9426,9426,9426
unique,6,2703,3,4,3,17,7,1263,4,49,1424
top,High,Louis Parrish,Regular Air,Corporate,Office Supplies,Paper,Small Box,"Global High-Back Leather Tilter, Burgundy",Central,California,New York City
freq,1970,27,7036,3375,5181,1379,4887,27,2899,1021,202

## Subsetting Columns

This is the act of selecting  a few columns from the entire dataframe.

In [ ]:
#Selecting a single colung using [] make it a series
df_dscount = dataDf['Discount']
print(type(df_dscount))
df_dscount.head()

<class 'pandas.core.series.Series'>

0    0.01
1    0.01
2    0.03
3    0.01
4    0.00
Name: Discount, dtype: float64

In [ ]:
#selcting single column discount and making it a dataframe, use [[]]
df_dscount = dataDf[['Discount']]
print(type(df_dscount))
df_dscount.head()

<class 'pandas.core.frame.DataFrame'>

   Discount
0      0.01
1      0.01
2      0.03
3      0.01
4      0.00

In [ ]:
#anaother way of selecting a single column without white space
df_dscount = dataDf.Discount
df_dscount

0       0.01
1       0.01
2       0.03
3       0.01
4       0.00
        ...
9421    0.06
9422    0.00
9423    0.08
9424    0.10
9425    0.09
Name: Discount, Length: 9426, dtype: float64

In [ ]:
dataDf.columns

Index(['Row ID', 'Order Priority', 'Discount', 'Unit Price', 'Shipping Cost',
       'Customer ID', 'Customer Name', 'Ship Mode', 'Customer Segment',
       'Product Category', 'Product Sub-Category', 'Product Container',
       'Product Name', 'Product Base Margin', 'Region', 'State or Province',
       'City', 'Postal Code', 'Order Date', 'Ship Date', 'Profit',
       'Quantity ordered new', 'Sales', 'Order ID'],
      dtype='object')

In [ ]:
#selcting the specific columns# use df[['col1', 'col2', 'col3']] e.g. selsct Order Date, Product Date, and ship mode
df_sub2 =dataDf[['Order Priority', 'Discount', 'Unit Price', 'Shipping Cost']]
df_sub2.head()

  Order Priority  Discount  Unit Price  Shipping Cost
0  Not Specified      0.01        2.88           0.50
1           High      0.01        2.84           0.93
2  Not Specified      0.03        6.68           6.15
3  Not Specified      0.01        5.68           3.60
4  Not Specified      0.00      205.99           2.50

In [ ]:
# we can use slicing as well e.g. df[df.columns[:5]]
dataDf[dataDf.columns[4:11]]

,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,Product Sub-Category
0,0.50,2,Janice Fletcher,Regular Air,Corporate,Office Supplies,Labels
1,0.93,3,Bonnie Potter,Express Air,Corporate,Office Supplies,Pens & Art Supplies
2,6.15,3,Bonnie Potter,Express Air,Corporate,Office Supplies,Paper
3,3.60,3,Bonnie Potter,Regular Air,Corporate,Office Supplies,"Scissors, Rulers and Trimmers"
4,2.50,3,Bonnie Potter,Express Air,Corporate,Technology,Telephones and Communication
...,...,...,...,...,...,...,...
9421,14.72,3402,Frederick Cole,Regular Air,Consumer,Office Supplies,Envelopes
9422,7.49,3402,Frederick Cole,Regular Air,Consumer,Office Supplies,Pens & Art Supplies
9423,45.70,3402,Frederick Cole,Delivery Truck,Consumer,Furniture,Tables
9424,13.99,3403,Tammy Buckley,Express Air,Consumer,Furniture,Office Furnishings
9425,2.50,3403,Tammy Buckley,Express Air,Consumer,Office Supplies,Envelopes

In [ ]:
#Using list comprehnsion e.g df[[c for c in df.columns]] to preview the dataset
#dataDf[[c for c in dataDf.columns]]

## Select dtypes

In [ ]:
#checking the data type
dataDf.dtypes

Row ID                           int64
Order Priority                  object
Discount                       float64
Unit Price                     float64
Shipping Cost                  float64
Customer ID                      int64
Customer Name                   object
Ship Mode                       object
Customer Segment                object
Product Category                object
Product Sub-Category            object
Product Container               object
Product Name                    object
Product Base Margin            float64
Region                          object
State or Province               object
City                            object
Postal Code                      int64
Order Date              datetime64[ns]
Ship Date               datetime64[ns]
Profit                         float64
Quantity ordered new             int64
Sales                          float64
Order ID                         int64
dtype: object

In [ ]:
# Selecting the numerical variables use df.select_dtypes(), include what you want to select as an argument
# you can change int to object and rerun the code.

dataDf.select_dtypes("O")  # chnage "O" with "number" for numerical values

,Order Priority,Customer Name,Ship Mode,Customer Segment,Product Category,Product Sub-Category,Product Container,Product Name,Region,State or Province,City
0,Not Specified,Janice Fletcher,Regular Air,Corporate,Office Supplies,Labels,Small Box,Avery 49,Central,Illinois,Addison
1,High,Bonnie Potter,Express Air,Corporate,Office Supplies,Pens & Art Supplies,Wrap Bag,SANFORD Liquid Accent™ Tank-Style Highlighters,West,Washington,Anacortes
2,Not Specified,Bonnie Potter,Express Air,Corporate,Office Supplies,Paper,Small Box,Xerox 1968,West,Washington,Anacortes
3,Not Specified,Bonnie Potter,Regular Air,Corporate,Office Supplies,"Scissors, Rulers and Trimmers",Small Pack,Acme® Preferred Stainless Steel Scissors,West,Washington,Anacortes
4,Not Specified,Bonnie Potter,Express Air,Corporate,Technology,Telephones and Communication,Small Box,V70,West,Washington,Anacortes
...,...,...,...,...,...,...,...,...,...,...,...
9421,Critical,Frederick Cole,Regular Air,Consumer,Office Supplies,Envelopes,Small Box,Jet-Pak Recycled Peel 'N' Seal Padded Mailers,East,West Virginia,Charleston
9422,Critical,Frederick Cole,Regular Air,Consumer,Office Supplies,Pens & Art Supplies,Wrap Bag,"Eldon Spacemaker® Box, Quick-Snap Lid, Clear",East,West Virginia,Charleston
9423,Not Specified,Frederick Cole,Delivery Truck,Consumer,Furniture,Tables,Jumbo Box,Chromcraft Bull-Nose Wood Oval Conference Tabl...,East,West Virginia,Charleston
9424,High,Tammy Buckley,Express Air,Consumer,Furniture,Office Furnishings,Medium Box,"Tenex 46"" x 60"" Computer Anti-Static Chairmat,...",West,Wyoming,Cheyenne
9425,Not Specified,Tammy Buckley,Express Air,Consumer,Office Supplies,Envelopes,Small Box,Staples #10 Colored Envelopes,West,Wyoming,Cheyenne

## Select as series vs dataframe

In [ ]:
#checking the series, use df['Col name']
dataDf["Discount"]

In [ ]:
#making the above as a dataframe , use df[['col name']]
dataDf[["Discount"]]

## loc and iloc

We can use loc(variable location), and iloc(index location) to access the variables as well

### iloc