<a href="https://colab.research.google.com/github/joyangelai/Colabs/blob/main/cohort2_pandas1_tutorial_(2).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas

In [ ]:
#Import pandas and numpy
import pandas as pd # for data manipulation and analysis
import numpy as np # used for mathematical computation # built on top of pandas

Data stractures used in pandas
1. pandas series
2. pandas data Frame

In [ ]:
#Create a  num and str list and convert it to a series
a = ["car", "boat", "bike"] #list

series1 = pd.Series(a)
print(series1)
print(type(series1))

0     car
1    boat
2    bike
dtype: object
<class 'pandas.core.series.Series'>

In [ ]:
#create a list and convert it to a dataframe
a = [("car", 100), ("boat", 70), ("bike", 40)]

df = pd.DataFrame(a, columns=("item", "price"))
print(df)
type(df)

   item  price
0   car    100
1  boat     70
2  bike     40

pandas.core.frame.DataFrame

In [ ]:
df.to_csv('df.csv', index=None)

In [ ]:
#load

In [ ]:
#save the dataframe to csv file
df.to_csv("item.csv", index =None)

In [ ]:
#load the saved item dataset
df2 = pd.read_csv("item.csv")
df2

   item  price
0   car    100
1  boat     70
2  bike     40

In [ ]:
#prove that the dataframe is made up of more than one series

df_price = df['price']
type(df_price)

pandas.core.series.Series

## Reading from files

In [ ]:
#Loading the dataset #excel dataset
dataDf =pd.read_excel('Sample_Superstore.xlsx')

dataDf

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,...,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
0,18606,Not Specified,0.01,2.88,0.50,2,Janice Fletcher,Regular Air,Corporate,Office Supplies,...,Central,Illinois,Addison,60101,2012-05-28,2012-05-30,1.320000,2,5.90,88525
1,20847,High,0.01,2.84,0.93,3,Bonnie Potter,Express Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221,2010-07-07,2010-07-08,4.560000,4,13.01,88522
2,23086,Not Specified,0.03,6.68,6.15,3,Bonnie Potter,Express Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221,2011-07-27,2011-07-28,-47.640000,7,49.92,88523
3,23087,Not Specified,0.01,5.68,3.60,3,Bonnie Potter,Regular Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221,2011-07-27,2011-07-28,-30.510000,7,41.64,88523
4,23088,Not Specified,0.00,205.99,2.50,3,Bonnie Potter,Express Air,Corporate,Technology,...,West,Washington,Anacortes,98221,2011-07-27,2011-07-27,998.202300,8,1446.67,88523
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9421,20275,Critical,0.06,35.89,14.72,3402,Frederick Cole,Regular Air,Consumer,Office Supplies,...,East,West Virginia,Charleston,25314,2013-05-14,2013-05-15,137.860000,13,447.87,87532
9422,20276,Critical,0.00,3.34,7.49,3402,Frederick Cole,Regular Air,Consumer,Office Supplies,...,East,West Virginia,Charleston,25314,2013-05-14,2013-05-14,-39.070000,3,13.23,87532
9423,24491,Not Specified,0.08,550.98,45.70,3402,Frederick Cole,Delivery Truck,Consumer,Furniture,...,East,West Virginia,Charleston,25314,2013-09-12,2013-09-14,-1225.029097,4,2215.93,87533
9424,25914,High,0.10,105.98,13.99,3403,Tammy Buckley,Express Air,Consumer,Furniture,...,West,Wyoming,Cheyenne,82001,2010-02-08,2010-02-11,349.485000,5,506.50,87530
9425,24492,Not Specified,0.09,7.78,2.50,3403,Tammy Buckley,Express Air,Consumer,Office Supplies,...,West,Wyoming,Cheyenne,82001,2013-09-12,2013-09-14,78.062400,23,172.48,87533

## Writing to files

In [ ]:
#saving the file to csv # use to_csv() and set index = False
data.to_csv("superstore.csv", index=None)

NameError: name 'data' is not defined

In [ ]:
datasv = pd.read_csv("superstore.csv")
datasv

## Dataframe basics

In [ ]:
#setting the default data view # pd.set_option("display.max_columns", 500)
pd.set_option("display.max_column", 200)

In [ ]:
#display the data
dataDf

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,Product Sub-Category,Product Container,Product Name,Product Base Margin,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
0,18606,Not Specified,0.01,2.88,0.50,2,Janice Fletcher,Regular Air,Corporate,Office Supplies,Labels,Small Box,Avery 49,0.36,Central,Illinois,Addison,60101,2012-05-28,2012-05-30,1.320000,2,5.90,88525
1,20847,High,0.01,2.84,0.93,3,Bonnie Potter,Express Air,Corporate,Office Supplies,Pens & Art Supplies,Wrap Bag,SANFORD Liquid Accent™ Tank-Style Highlighters,0.54,West,Washington,Anacortes,98221,2010-07-07,2010-07-08,4.560000,4,13.01,88522
2,23086,Not Specified,0.03,6.68,6.15,3,Bonnie Potter,Express Air,Corporate,Office Supplies,Paper,Small Box,Xerox 1968,0.37,West,Washington,Anacortes,98221,2011-07-27,2011-07-28,-47.640000,7,49.92,88523
3,23087,Not Specified,0.01,5.68,3.60,3,Bonnie Potter,Regular Air,Corporate,Office Supplies,"Scissors, Rulers and Trimmers",Small Pack,Acme® Preferred Stainless Steel Scissors,0.56,West,Washington,Anacortes,98221,2011-07-27,2011-07-28,-30.510000,7,41.64,88523
4,23088,Not Specified,0.00,205.99,2.50,3,Bonnie Potter,Express Air,Corporate,Technology,Telephones and Communication,Small Box,V70,0.59,West,Washington,Anacortes,98221,2011-07-27,2011-07-27,998.202300,8,1446.67,88523
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9421,20275,Critical,0.06,35.89,14.72,3402,Frederick Cole,Regular Air,Consumer,Office Supplies,Envelopes,Small Box,Jet-Pak Recycled Peel 'N' Seal Padded Mailers,0.40,East,West Virginia,Charleston,25314,2013-05-14,2013-05-15,137.860000,13,447.87,87532
9422,20276,Critical,0.00,3.34,7.49,3402,Frederick Cole,Regular Air,Consumer,Office Supplies,Pens & Art Supplies,Wrap Bag,"Eldon Spacemaker® Box, Quick-Snap Lid, Clear",0.54,East,West Virginia,Charleston,25314,2013-05-14,2013-05-14,-39.070000,3,13.23,87532
9423,24491,Not Specified,0.08,550.98,45.70,3402,Frederick Cole,Delivery Truck,Consumer,Furniture,Tables,Jumbo Box,Chromcraft Bull-Nose Wood Oval Conference Tabl...,0.71,East,West Virginia,Charleston,25314,2013-09-12,2013-09-14,-1225.029097,4,2215.93,87533
9424,25914,High,0.10,105.98,13.99,3403,Tammy Buckley,Express Air,Consumer,Furniture,Office Furnishings,Medium Box,"Tenex 46"" x 60"" Computer Anti-Static Chairmat,...",0.65,West,Wyoming,Cheyenne,82001,2010-02-08,2010-02-11,349.485000,5,506.50,87530
9425,24492,Not Specified,0.09,7.78,2.50,3403,Tammy Buckley,Express Air,Consumer,Office Supplies,Envelopes,Small Box,Staples #10 Colored Envelopes,0.38,West,Wyoming,Cheyenne,82001,2013-09-12,2013-09-14,78.062400,23,172.48,87533

### Initial Exploratory Data analysis (IDA)

In [ ]:
#checking a few top rows
dataDf.head()

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,Product Sub-Category,Product Container,Product Name,Product Base Margin,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
0,18606,Not Specified,0.01,2.88,0.50,2,Janice Fletcher,Regular Air,Corporate,Office Supplies,Labels,Small Box,Avery 49,0.36,Central,Illinois,Addison,60101,2012-05-28,2012-05-30,1.3200,2,5.90,88525
1,20847,High,0.01,2.84,0.93,3,Bonnie Potter,Express Air,Corporate,Office Supplies,Pens & Art Supplies,Wrap Bag,SANFORD Liquid Accent™ Tank-Style Highlighters,0.54,West,Washington,Anacortes,98221,2010-07-07,2010-07-08,4.5600,4,13.01,88522
2,23086,Not Specified,0.03,6.68,6.15,3,Bonnie Potter,Express Air,Corporate,Office Supplies,Paper,Small Box,Xerox 1968,0.37,West,Washington,Anacortes,98221,2011-07-27,2011-07-28,-47.6400,7,49.92,88523
3,23087,Not Specified,0.01,5.68,3.60,3,Bonnie Potter,Regular Air,Corporate,Office Supplies,"Scissors, Rulers and Trimmers",Small Pack,Acme® Preferred Stainless Steel Scissors,0.56,West,Washington,Anacortes,98221,2011-07-27,2011-07-28,-30.5100,7,41.64,88523
4,23088,Not Specified,0.00,205.99,2.50,3,Bonnie Potter,Express Air,Corporate,Technology,Telephones and Communication,Small Box,V70,0.59,West,Washington,Anacortes,98221,2011-07-27,2011-07-27,998.2023,8,1446.67,88523

In [ ]:
#Bottom 5 rows
dataDf.tail()

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,Product Sub-Category,Product Container,Product Name,Product Base Margin,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
9421,20275,Critical,0.06,35.89,14.72,3402,Frederick Cole,Regular Air,Consumer,Office Supplies,Envelopes,Small Box,Jet-Pak Recycled Peel 'N' Seal Padded Mailers,0.40,East,West Virginia,Charleston,25314,2013-05-14,2013-05-15,137.860000,13,447.87,87532
9422,20276,Critical,0.00,3.34,7.49,3402,Frederick Cole,Regular Air,Consumer,Office Supplies,Pens & Art Supplies,Wrap Bag,"Eldon Spacemaker® Box, Quick-Snap Lid, Clear",0.54,East,West Virginia,Charleston,25314,2013-05-14,2013-05-14,-39.070000,3,13.23,87532
9423,24491,Not Specified,0.08,550.98,45.70,3402,Frederick Cole,Delivery Truck,Consumer,Furniture,Tables,Jumbo Box,Chromcraft Bull-Nose Wood Oval Conference Tabl...,0.71,East,West Virginia,Charleston,25314,2013-09-12,2013-09-14,-1225.029097,4,2215.93,87533
9424,25914,High,0.10,105.98,13.99,3403,Tammy Buckley,Express Air,Consumer,Furniture,Office Furnishings,Medium Box,"Tenex 46"" x 60"" Computer Anti-Static Chairmat,...",0.65,West,Wyoming,Cheyenne,82001,2010-02-08,2010-02-11,349.485000,5,506.50,87530
9425,24492,Not Specified,0.09,7.78,2.50,3403,Tammy Buckley,Express Air,Consumer,Office Supplies,Envelopes,Small Box,Staples #10 Colored Envelopes,0.38,West,Wyoming,Cheyenne,82001,2013-09-12,2013-09-14,78.062400,23,172.48,87533

In [ ]:
#Displaying the top 3 rows #
dataDf.head(3)

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,Product Sub-Category,Product Container,Product Name,Product Base Margin,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
0,18606,Not Specified,0.01,2.88,0.50,2,Janice Fletcher,Regular Air,Corporate,Office Supplies,Labels,Small Box,Avery 49,0.36,Central,Illinois,Addison,60101,2012-05-28,2012-05-30,1.32,2,5.90,88525
1,20847,High,0.01,2.84,0.93,3,Bonnie Potter,Express Air,Corporate,Office Supplies,Pens & Art Supplies,Wrap Bag,SANFORD Liquid Accent™ Tank-Style Highlighters,0.54,West,Washington,Anacortes,98221,2010-07-07,2010-07-08,4.56,4,13.01,88522
2,23086,Not Specified,0.03,6.68,6.15,3,Bonnie Potter,Express Air,Corporate,Office Supplies,Paper,Small Box,Xerox 1968,0.37,West,Washington,Anacortes,98221,2011-07-27,2011-07-28,-47.64,7,49.92,88523

In [ ]:
#Displaying the last 3 rows #
dataDf.tail(3)

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,Product Sub-Category,Product Container,Product Name,Product Base Margin,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
9423,24491,Not Specified,0.08,550.98,45.70,3402,Frederick Cole,Delivery Truck,Consumer,Furniture,Tables,Jumbo Box,Chromcraft Bull-Nose Wood Oval Conference Tabl...,0.71,East,West Virginia,Charleston,25314,2013-09-12,2013-09-14,-1225.029097,4,2215.93,87533
9424,25914,High,0.10,105.98,13.99,3403,Tammy Buckley,Express Air,Consumer,Furniture,Office Furnishings,Medium Box,"Tenex 46"" x 60"" Computer Anti-Static Chairmat,...",0.65,West,Wyoming,Cheyenne,82001,2010-02-08,2010-02-11,349.485000,5,506.50,87530
9425,24492,Not Specified,0.09,7.78,2.50,3403,Tammy Buckley,Express Air,Consumer,Office Supplies,Envelopes,Small Box,Staples #10 Colored Envelopes,0.38,West,Wyoming,Cheyenne,82001,2013-09-12,2013-09-14,78.062400,23,172.48,87533

In [ ]:
#Displaying 3 random rows #use sample()
dataDf.sample(4)

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,Product Sub-Category,Product Container,Product Name,Product Base Margin,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
7324,5602,Not Specified,0.06,328.14,91.05,2670,Yvonne Mann,Delivery Truck,Home Office,Office Supplies,Appliances,Jumbo Drum,Sanyo Counter Height Refrigerator with Crisper...,0.57,West,California,Los Angeles,90049,2013-06-08,2013-06-09,-473.6600,3,1108.20,39686
6072,24904,Not Specified,0.04,17.98,8.51,2228,Beverly Baker,Regular Air,Corporate,Technology,Office Machines,Medium Box,Canon P1-DHIII Palm Printing Calculator,0.40,East,Pennsylvania,Radnor,19087,2011-07-03,2011-07-04,-15.4164,7,127.16,89156
3724,24257,Low,0.09,6.48,9.68,1409,Frederick Lehman,Express Air,Consumer,Office Supplies,Paper,Small Box,Xerox 1993,0.36,West,Utah,American Fork,84003,2013-06-03,2013-06-10,-68.2320,6,43.14,90448
3738,20626,Low,0.08,10.89,4.50,1411,Larry Neal,Regular Air,Corporate,Office Supplies,Appliances,Small Box,Belkin 6 Outlet Metallic Surge Strip,0.59,West,California,Morgan Hill,95037,2012-07-26,2012-07-30,-18.5000,1,12.02,87093

In [ ]:
#checking the columns # use columns attribute
dataDf.columns

Index(['Row ID', 'Order Priority', 'Discount', 'Unit Price', 'Shipping Cost',
       'Customer ID', 'Customer Name', 'Ship Mode', 'Customer Segment',
       'Product Category', 'Product Sub-Category', 'Product Container',
       'Product Name', 'Product Base Margin', 'Region', 'State or Province',
       'City', 'Postal Code', 'Order Date', 'Ship Date', 'Profit',
       'Quantity ordered new', 'Sales', 'Order ID'],
      dtype='object')

In [ ]:
#using list comprehesion
#Using list comprehnsion e.g [c for c in df.columns]
[c for c in dataDf.columns]

['Row ID',
 'Order Priority',
 'Discount',
 'Unit Price',
 'Shipping Cost',
 'Customer ID',
 'Customer Name',
 'Ship Mode',
 'Customer Segment',
 'Product Category',
 'Product Sub-Category',
 'Product Container',
 'Product Name',
 'Product Base Margin',
 'Region',
 'State or Province',
 'City',
 'Postal Code',
 'Order Date',
 'Ship Date',
 'Profit',
 'Quantity ordered new',
 'Sales',
 'Order ID']

In [ ]:
#checking the index # use df.index
dataDf.index

RangeIndex(start=0, stop=9426, step=1)

In [ ]:
#check the shape
dataDf.shape

(9426, 24)

In [ ]:
#getting records
len(dataDf)

9426

In [ ]:
#check the shape
print(f" This dataset has {dataDf.shape[0]} records and {dataDf.shape[1]} columns")

 This dataset has 9426 records and 24 columns

## Dataframe summary

In [ ]:
#Checking the data Summary # use info(), we can also use info(verbose=False)
dataDf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9426 entries, 0 to 9425
Data columns (total 24 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Row ID                9426 non-null   int64
 1   Order Priority        9426 non-null   object
 2   Discount              9426 non-null   float64
 3   Unit Price            9426 non-null   float64
 4   Shipping Cost         9426 non-null   float64
 5   Customer ID           9426 non-null   int64
 6   Customer Name         9426 non-null   object
 7   Ship Mode             9426 non-null   object
 8   Customer Segment      9426 non-null   object
 9   Product Category      9426 non-null   object
 10  Product Sub-Category  9426 non-null   object
 11  Product Container     9426 non-null   object
 12  Product Name          9426 non-null   object
 13  Product Base Margin   9354 non-null   float64
 14  Region                9426 non-null   object
 15  State or Province     9426 non-null   object
 16  City                  9426 non-null   object
 17  Postal Code           9426 non-null   int64
 18  Order Date            9426 non-null   datetime64[ns]
 19  Ship Date             9426 non-null   datetime64[ns]
 20  Profit                9426 non-null   float64
 21  Quantity ordered new  9426 non-null   int64
 22  Sales                 9426 non-null   float64
 23  Order ID              9426 non-null   int64
dtypes: datetime64[ns](2), float64(6), int64(5), object(11)
memory usage: 1.7+ MB

In [ ]:
# incoperating verbose argument
dataDf.info(verbose=False)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9426 entries, 0 to 9425
Columns: 24 entries, Row ID to Order ID
dtypes: datetime64[ns](2), float64(6), int64(5), object(11)
memory usage: 1.7+ MB

In [ ]:
#Checking concise Descriptive statistics for numerical variables# use .describe
dataDf.describe().T

,count,mean,min,25%,50%,75%,max,std
Row ID,9426.0,20241.015277,2.0,19330.25,21686.5,24042.75,26399.0,6101.890965
Discount,9426.0,0.049628,0.0,0.02,0.05,0.08,0.25,0.031798
Unit Price,9426.0,88.303686,0.99,6.48,20.99,85.99,6783.02,281.540982
Shipping Cost,9426.0,12.795142,0.49,3.1925,6.05,13.99,164.73,17.181203
Customer ID,9426.0,1738.422236,2.0,898.0,1750.0,2578.75,3403.0,979.167197
Product Base Margin,9354.0,0.512189,0.35,0.38,0.52,0.59,0.85,0.135229
Postal Code,9426.0,52446.327286,1001.0,29406.0,52302.0,78516.0,99362.0,29374.597802
Order Date,9426,2012-03-05 18:33:59.465308672,2010-01-01 00:00:00,2011-03-07 06:00:00,2012-04-08 00:00:00,2013-03-26 00:00:00,2013-12-31 00:00:00,NaN
Ship Date,9426,2012-03-07 19:16:18.485041408,2010-01-02 00:00:00,2011-03-09 00:00:00,2012-04-09 00:00:00,2013-03-28 00:00:00,2014-01-17 00:00:00,NaN
Profit,9426.0,139.23641,-16476.838,-74.017375,2.5676,140.24385,16332.414,998.486483
Quantity ordered new,9426.0,13.79843,1.0,5.0,10.0,17.0,170.0,15.107688
Sales,9426.0,949.706272,1.32,61.2825,203.455,776.4025,100119.16,2598.019818
Order ID,9426.0,82318.489073,6.0,86737.25,88344.5,89987.75,91591.0,19149.448857

In [ ]:
#summary stst for numerical values
dataDf.describe(include = (["float", "int"]))

,Row ID,Discount,Unit Price,Shipping Cost,Customer ID,Product Base Margin,Postal Code,Profit,Quantity ordered new,Sales,Order ID
count,9426.000000,9426.000000,9426.000000,9426.000000,9426.000000,9354.000000,9426.000000,9426.000000,9426.000000,9426.000000,9426.000000
mean,20241.015277,0.049628,88.303686,12.795142,1738.422236,0.512189,52446.327286,139.236410,13.798430,949.706272,82318.489073
std,6101.890965,0.031798,281.540982,17.181203,979.167197,0.135229,29374.597802,998.486483,15.107688,2598.019818,19149.448857
min,2.000000,0.000000,0.990000,0.490000,2.000000,0.350000,1001.000000,-16476.838000,1.000000,1.320000,6.000000
25%,19330.250000,0.020000,6.480000,3.192500,898.000000,0.380000,29406.000000,-74.017375,5.000000,61.282500,86737.250000
50%,21686.500000,0.050000,20.990000,6.050000,1750.000000,0.520000,52302.000000,2.567600,10.000000,203.455000,88344.500000
75%,24042.750000,0.080000,85.990000,13.990000,2578.750000,0.590000,78516.000000,140.243850,17.000000,776.402500,89987.750000
max,26399.000000,0.250000,6783.020000,164.730000,3403.000000,0.850000,99362.000000,16332.414000,170.000000,100119.160000,91591.000000

In [ ]:
#Checking concise Descriptive statistics for categorical variables# use coln.describe()
dataDf.describe(include = 'O').T  # you can use object

,count,unique,top,freq
Order Priority,9426,6,High,1970
Customer Name,9426,2703,Louis Parrish,27
Ship Mode,9426,3,Regular Air,7036
Customer Segment,9426,4,Corporate,3375
Product Category,9426,3,Office Supplies,5181
Product Sub-Category,9426,17,Paper,1379
Product Container,9426,7,Small Box,4887
Product Name,9426,1263,"Global High-Back Leather Tilter, Burgundy",27
Region,9426,4,Central,2899
State or Province,9426,49,California,1021
City,9426,1424,New York City,202

In [ ]:
#another way of checking cat summary stst
dataDf.describe(include = 'object')  # you can use object

,Order Priority,Customer Name,Ship Mode,Customer Segment,Product Category,Product Sub-Category,Product Container,Product Name,Region,State or Province,City
count,9426,9426,9426,9426,9426,9426,9426,9426,9426,9426,9426
unique,6,2703,3,4,3,17,7,1263,4,49,1424
top,High,Louis Parrish,Regular Air,Corporate,Office Supplies,Paper,Small Box,"Global High-Back Leather Tilter, Burgundy",Central,California,New York City
freq,1970,27,7036,3375,5181,1379,4887,27,2899,1021,202

## Subsetting Columns

This is the act of selecting  a few columns from the entire dataframe.

In [ ]:
#Selecting a single colung using [] make it a series
df_dscount = dataDf['Discount']
print(type(df_dscount))
df_dscount.head()

<class 'pandas.core.series.Series'>

0    0.01
1    0.01
2    0.03
3    0.01
4    0.00
Name: Discount, dtype: float64

In [ ]:
#selcting single column discount and making it a dataframe, use [[]]
df_dscount = dataDf[['Discount']]
print(type(df_dscount))
df_dscount.head()

<class 'pandas.core.frame.DataFrame'>

   Discount
0      0.01
1      0.01
2      0.03
3      0.01
4      0.00

In [ ]:
#anaother way of selecting a single column without white space
df_dscount = dataDf.Discount
df_dscount

0       0.01
1       0.01
2       0.03
3       0.01
4       0.00
        ...
9421    0.06
9422    0.00
9423    0.08
9424    0.10
9425    0.09
Name: Discount, Length: 9426, dtype: float64

In [ ]:
dataDf.columns

Index(['Row ID', 'Order Priority', 'Discount', 'Unit Price', 'Shipping Cost',
       'Customer ID', 'Customer Name', 'Ship Mode', 'Customer Segment',
       'Product Category', 'Product Sub-Category', 'Product Container',
       'Product Name', 'Product Base Margin', 'Region', 'State or Province',
       'City', 'Postal Code', 'Order Date', 'Ship Date', 'Profit',
       'Quantity ordered new', 'Sales', 'Order ID'],
      dtype='object')

In [ ]:
#selcting the specific columns# use df[['col1', 'col2', 'col3']] e.g. selsct Order Date, Product Date, and ship mode
df_sub2 =dataDf[['Order Priority', 'Discount', 'Unit Price', 'Shipping Cost']]
df_sub2.head()

  Order Priority  Discount  Unit Price  Shipping Cost
0  Not Specified      0.01        2.88           0.50
1           High      0.01        2.84           0.93
2  Not Specified      0.03        6.68           6.15
3  Not Specified      0.01        5.68           3.60
4  Not Specified      0.00      205.99           2.50

In [ ]:
# we can use slicing as well e.g. df[df.columns[:5]]
dataDf[dataDf.columns[4:11]]

,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,Product Sub-Category
0,0.50,2,Janice Fletcher,Regular Air,Corporate,Office Supplies,Labels
1,0.93,3,Bonnie Potter,Express Air,Corporate,Office Supplies,Pens & Art Supplies
2,6.15,3,Bonnie Potter,Express Air,Corporate,Office Supplies,Paper
3,3.60,3,Bonnie Potter,Regular Air,Corporate,Office Supplies,"Scissors, Rulers and Trimmers"
4,2.50,3,Bonnie Potter,Express Air,Corporate,Technology,Telephones and Communication
...,...,...,...,...,...,...,...
9421,14.72,3402,Frederick Cole,Regular Air,Consumer,Office Supplies,Envelopes
9422,7.49,3402,Frederick Cole,Regular Air,Consumer,Office Supplies,Pens & Art Supplies
9423,45.70,3402,Frederick Cole,Delivery Truck,Consumer,Furniture,Tables
9424,13.99,3403,Tammy Buckley,Express Air,Consumer,Furniture,Office Furnishings
9425,2.50,3403,Tammy Buckley,Express Air,Consumer,Office Supplies,Envelopes

In [ ]:
#Using list comprehnsion e.g df[[c for c in df.columns]] to preview the dataset
#dataDf[[c for c in dataDf.columns]]

## Select dtypes

In [ ]:
#checking the data type
dataDf.dtypes

Row ID                           int64
Order Priority                  object
Discount                       float64
Unit Price                     float64
Shipping Cost                  float64
Customer ID                      int64
Customer Name                   object
Ship Mode                       object
Customer Segment                object
Product Category                object
Product Sub-Category            object
Product Container               object
Product Name                    object
Product Base Margin            float64
Region                          object
State or Province               object
City                            object
Postal Code                      int64
Order Date              datetime64[ns]
Ship Date               datetime64[ns]
Profit                         float64
Quantity ordered new             int64
Sales                          float64
Order ID                         int64
dtype: object

In [ ]:
# Selecting the numerical variables use df.select_dtypes(), include what you want to select as an argument
# you can change int to object and rerun the code.

dataDf.select_dtypes("O")  # chnage "O" with "number" for numerical values

,Order Priority,Customer Name,Ship Mode,Customer Segment,Product Category,Product Sub-Category,Product Container,Product Name,Region,State or Province,City
0,Not Specified,Janice Fletcher,Regular Air,Corporate,Office Supplies,Labels,Small Box,Avery 49,Central,Illinois,Addison
1,High,Bonnie Potter,Express Air,Corporate,Office Supplies,Pens & Art Supplies,Wrap Bag,SANFORD Liquid Accent™ Tank-Style Highlighters,West,Washington,Anacortes
2,Not Specified,Bonnie Potter,Express Air,Corporate,Office Supplies,Paper,Small Box,Xerox 1968,West,Washington,Anacortes
3,Not Specified,Bonnie Potter,Regular Air,Corporate,Office Supplies,"Scissors, Rulers and Trimmers",Small Pack,Acme® Preferred Stainless Steel Scissors,West,Washington,Anacortes
4,Not Specified,Bonnie Potter,Express Air,Corporate,Technology,Telephones and Communication,Small Box,V70,West,Washington,Anacortes
...,...,...,...,...,...,...,...,...,...,...,...
9421,Critical,Frederick Cole,Regular Air,Consumer,Office Supplies,Envelopes,Small Box,Jet-Pak Recycled Peel 'N' Seal Padded Mailers,East,West Virginia,Charleston
9422,Critical,Frederick Cole,Regular Air,Consumer,Office Supplies,Pens & Art Supplies,Wrap Bag,"Eldon Spacemaker® Box, Quick-Snap Lid, Clear",East,West Virginia,Charleston
9423,Not Specified,Frederick Cole,Delivery Truck,Consumer,Furniture,Tables,Jumbo Box,Chromcraft Bull-Nose Wood Oval Conference Tabl...,East,West Virginia,Charleston
9424,High,Tammy Buckley,Express Air,Consumer,Furniture,Office Furnishings,Medium Box,"Tenex 46"" x 60"" Computer Anti-Static Chairmat,...",West,Wyoming,Cheyenne
9425,Not Specified,Tammy Buckley,Express Air,Consumer,Office Supplies,Envelopes,Small Box,Staples #10 Colored Envelopes,West,Wyoming,Cheyenne

## Select as series vs dataframe

In [ ]:
#checking the series, use df['Col name']
dataDf["Discount"]

0       0.01
1       0.01
2       0.03
3       0.01
4       0.00
        ...
9421    0.06
9422    0.00
9423    0.08
9424    0.10
9425    0.09
Name: Discount, Length: 9426, dtype: float64

In [ ]:
#making the above as a dataframe , use df[['col name']]
dataDf[["Discount"]]

      Discount
0         0.01
1         0.01
2         0.03
3         0.01
4         0.00
...        ...
9421      0.06
9422      0.00
9423      0.08
9424      0.10
9425      0.09

[9426 rows x 1 columns]

## loc and iloc

We can use loc(variable location), and iloc(index location) to access the variables as well

### iloc

In [ ]:
#checking the dataset
dataDf.head()

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,Product Sub-Category,Product Container,Product Name,Product Base Margin,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
0,18606,Not Specified,0.01,2.88,0.50,2,Janice Fletcher,Regular Air,Corporate,Office Supplies,Labels,Small Box,Avery 49,0.36,Central,Illinois,Addison,60101,2012-05-28,2012-05-30,1.3200,2,5.90,88525
1,20847,High,0.01,2.84,0.93,3,Bonnie Potter,Express Air,Corporate,Office Supplies,Pens & Art Supplies,Wrap Bag,SANFORD Liquid Accent™ Tank-Style Highlighters,0.54,West,Washington,Anacortes,98221,2010-07-07,2010-07-08,4.5600,4,13.01,88522
2,23086,Not Specified,0.03,6.68,6.15,3,Bonnie Potter,Express Air,Corporate,Office Supplies,Paper,Small Box,Xerox 1968,0.37,West,Washington,Anacortes,98221,2011-07-27,2011-07-28,-47.6400,7,49.92,88523
3,23087,Not Specified,0.01,5.68,3.60,3,Bonnie Potter,Regular Air,Corporate,Office Supplies,"Scissors, Rulers and Trimmers",Small Pack,Acme® Preferred Stainless Steel Scissors,0.56,West,Washington,Anacortes,98221,2011-07-27,2011-07-28,-30.5100,7,41.64,88523
4,23088,Not Specified,0.00,205.99,2.50,3,Bonnie Potter,Express Air,Corporate,Technology,Telephones and Communication,Small Box,V70,0.59,West,Washington,Anacortes,98221,2011-07-27,2011-07-27,998.2023,8,1446.67,88523

In [ ]:
# getting the value using iloc e.g df.iloc[1], getting one row and all columns
dataDf.iloc[1]

Row ID                                                           20847
Order Priority                                                    High
Discount                                                          0.01
Unit Price                                                        2.84
Shipping Cost                                                     0.93
Customer ID                                                          3
Customer Name                                            Bonnie Potter
Ship Mode                                                  Express Air
Customer Segment                                             Corporate
Product Category                                       Office Supplies
Product Sub-Category                               Pens & Art Supplies
Product Container                                             Wrap Bag
Product Name            SANFORD Liquid Accent™ Tank-Style Highlighters
Product Base Margin                                               0.54
Region                                                            West
State or Province                                           Washington
City                                                         Anacortes
Postal Code                                                      98221
Order Date                                         2010-07-07 00:00:00
Ship Date                                          2010-07-08 00:00:00
Profit                                                            4.56
Quantity ordered new                                                 4
Sales                                                            13.01
Order ID                                                         88522
Name: 1, dtype: object

In [ ]:
#get value for row 1 and column 1
dataDf.iloc[2, 1]

'Not Specified'

In [ ]:
#slicing e.g df.iloc[:5, :5]
dataDf.iloc[:4, :4]

   Row ID Order Priority  Discount  Unit Price
0   18606  Not Specified      0.01        2.88
1   20847           High      0.01        2.84
2   23086  Not Specified      0.03        6.68
3   23087  Not Specified      0.01        5.68

In [ ]:
list1 = [2,4,6,7,6]
list1[2:4]

[6, 7]

In [ ]:
#get first 4 rows and column 2 and 7
dataDf.iloc[:4, [2, 7]]

   Discount    Ship Mode
0      0.01  Regular Air
1      0.01  Express Air
2      0.03  Express Air
3      0.01  Regular Air

In [ ]:
# get row index 1 and 4, then column index 2 and 7
dataDf.iloc[[1,4], [2, 7]]

   Discount    Ship Mode
1      0.01  Express Air
4      0.00  Express Air

In [ ]:
#Getting specific row e.g df.iloc[5], we can present our result in dataframe formart as well

In [ ]:
#Checking the index 1 columns e.g df.iloc[:, 1]

In [ ]:
#getting index 1 and 2 columns, e.g  df.iloc[:, [1, 2]]
dataDf.iloc[:, [1,6]]

     Order Priority    Customer Name
0     Not Specified  Janice Fletcher
1              High    Bonnie Potter
2     Not Specified    Bonnie Potter
3     Not Specified    Bonnie Potter
4     Not Specified    Bonnie Potter
...             ...              ...
9421       Critical   Frederick Cole
9422       Critical   Frederick Cole
9423  Not Specified   Frederick Cole
9424           High    Tammy Buckley
9425  Not Specified    Tammy Buckley

[9426 rows x 2 columns]

Loc

we use loc when we want to select the variable by the name

In [ ]:
dataDf.head()

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,Product Sub-Category,Product Container,Product Name,Product Base Margin,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
0,18606,Not Specified,0.01,2.88,0.50,2,Janice Fletcher,Regular Air,Corporate,Office Supplies,Labels,Small Box,Avery 49,0.36,Central,Illinois,Addison,60101,2012-05-28,2012-05-30,1.3200,2,5.90,88525
1,20847,High,0.01,2.84,0.93,3,Bonnie Potter,Express Air,Corporate,Office Supplies,Pens & Art Supplies,Wrap Bag,SANFORD Liquid Accent™ Tank-Style Highlighters,0.54,West,Washington,Anacortes,98221,2010-07-07,2010-07-08,4.5600,4,13.01,88522
2,23086,Not Specified,0.03,6.68,6.15,3,Bonnie Potter,Express Air,Corporate,Office Supplies,Paper,Small Box,Xerox 1968,0.37,West,Washington,Anacortes,98221,2011-07-27,2011-07-28,-47.6400,7,49.92,88523
3,23087,Not Specified,0.01,5.68,3.60,3,Bonnie Potter,Regular Air,Corporate,Office Supplies,"Scissors, Rulers and Trimmers",Small Pack,Acme® Preferred Stainless Steel Scissors,0.56,West,Washington,Anacortes,98221,2011-07-27,2011-07-28,-30.5100,7,41.64,88523
4,23088,Not Specified,0.00,205.99,2.50,3,Bonnie Potter,Express Air,Corporate,Technology,Telephones and Communication,Small Box,V70,0.59,West,Washington,Anacortes,98221,2011-07-27,2011-07-27,998.2023,8,1446.67,88523

In [ ]:
dataDf.columns

Index(['Row ID', 'Order Priority', 'Discount', 'Unit Price', 'Shipping Cost',
       'Customer ID', 'Customer Name', 'Ship Mode', 'Customer Segment',
       'Product Category', 'Product Sub-Category', 'Product Container',
       'Product Name', 'Product Base Margin', 'Region', 'State or Province',
       'City', 'Postal Code', 'Order Date', 'Ship Date', 'Profit',
       'Quantity ordered new', 'Sales', 'Order ID'],
      dtype='object')

In [ ]:
#subsetting  2 columns df.loc[:, ['col1', 'col2']]
dataDf.loc[[2,5,7], ["Discount",'Ship Mode' ]]

   Discount       Ship Mode
2      0.03     Express Air
5      0.09     Express Air
7      0.02  Delivery Truck

In [ ]:
#checking subclasses
x = dataDf['Customer Segment']
x.unique()

array(['Corporate', 'Home Office', 'Small Business', 'Consumer'],
      dtype=object)

In [ ]:
dataDf[17:20]

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,Product Sub-Category,Product Container,Product Name,Product Base Margin,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
17,21776,Critical,0.06,9.48,7.29,11,Marcus Dunlap,Regular Air,Home Office,Furniture,Office Furnishings,Small Pack,"DAX Two-Tone Rosewood/Black Document Frame, De...",0.45,East,New Jersey,Roselle,7203,2010-08-15,2010-08-17,-53.8096,22,211.15,90192
18,23328,High,0.04,10.98,3.37,12,Kara Pace,Regular Air,Home Office,Office Supplies,"Scissors, Rulers and Trimmers",Small Pack,Fiskars® Softgrip Scissors,0.57,East,Rhode Island,Cranston,2907,2012-02-24,2012-02-26,23.1200,8,90.39,90196
19,24844,Medium,0.09,78.69,19.99,14,Gwendolyn F Tyson,Regular Air,Small Business,Furniture,Office Furnishings,Small Box,Howard Miller 12-3/4 Diameter Accuwave DS ™ Wa...,0.43,Central,Minnesota,Prior Lake,55372,2010-05-12,2010-05-14,803.4705,16,1164.45,86838

In [ ]:
dataDf.columns

Index(['Row ID', 'Order Priority', 'Discount', 'Unit Price', 'Shipping Cost',
       'Customer ID', 'Customer Name', 'Ship Mode', 'Customer Segment',
       'Product Category', 'Product Sub-Category', 'Product Container',
       'Product Name', 'Product Base Margin', 'Region', 'State or Province',
       'City', 'Postal Code', 'Order Date', 'Ship Date', 'Profit',
       'Quantity ordered new', 'Sales', 'Order ID'],
      dtype='object')

In [ ]:
#coverting column to index
detaind = dataDf.copy(deep=True)


#using index
detaind.index = dataind['Customer Name']
detaind.head()

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,Product Sub-Category,Product Container,Product Name,Product Base Margin,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
Customer Name,,,,,,,,,,,,,,,,,,,,,,,,
Janice Fletcher,18606,Not Specified,0.01,2.88,0.50,2,Janice Fletcher,Regular Air,Corporate,Office Supplies,Labels,Small Box,Avery 49,0.36,Central,Illinois,Addison,60101,2012-05-28,2012-05-30,1.3200,2,5.90,88525
Bonnie Potter,20847,High,0.01,2.84,0.93,3,Bonnie Potter,Express Air,Corporate,Office Supplies,Pens & Art Supplies,Wrap Bag,SANFORD Liquid Accent™ Tank-Style Highlighters,0.54,West,Washington,Anacortes,98221,2010-07-07,2010-07-08,4.5600,4,13.01,88522
Bonnie Potter,23086,Not Specified,0.03,6.68,6.15,3,Bonnie Potter,Express Air,Corporate,Office Supplies,Paper,Small Box,Xerox 1968,0.37,West,Washington,Anacortes,98221,2011-07-27,2011-07-28,-47.6400,7,49.92,88523
Bonnie Potter,23087,Not Specified,0.01,5.68,3.60,3,Bonnie Potter,Regular Air,Corporate,Office Supplies,"Scissors, Rulers and Trimmers",Small Pack,Acme® Preferred Stainless Steel Scissors,0.56,West,Washington,Anacortes,98221,2011-07-27,2011-07-28,-30.5100,7,41.64,88523
Bonnie Potter,23088,Not Specified,0.00,205.99,2.50,3,Bonnie Potter,Express Air,Corporate,Technology,Telephones and Communication,Small Box,V70,0.59,West,Washington,Anacortes,98221,2011-07-27,2011-07-27,998.2023,8,1446.67,88523

#### loc filter expressions

we can use loc filter to get specific records

In [ ]:
data_sma["Customer Segment"].unique()

array(['Small Business'], dtype=object)

In [ ]:
#Get the records of a specific value e.g  df.loc[df['Region'] == 'West']
data_sma = dataDf[dataDf['Customer Segment']== "Small Business"]
data_sma.head()

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,Product Sub-Category,Product Container,Product Name,Product Base Margin,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
19,24844,Medium,0.09,78.69,19.99,14,Gwendolyn F Tyson,Regular Air,Small Business,Furniture,Office Furnishings,Small Box,Howard Miller 12-3/4 Diameter Accuwave DS ™ Wa...,0.43,Central,Minnesota,Prior Lake,55372,2010-05-12,2010-05-14,803.4705,16,1164.45,86838
20,24846,Medium,0.08,3.28,2.31,14,Gwendolyn F Tyson,Regular Air,Small Business,Office Supplies,Pens & Art Supplies,Wrap Bag,Newell 321,0.56,Central,Minnesota,Prior Lake,55372,2010-05-12,2010-05-13,-24.0300,7,22.23,86838
21,24847,Medium,0.05,3.28,4.20,14,Gwendolyn F Tyson,Regular Air,Small Business,Office Supplies,Pens & Art Supplies,Wrap Bag,Newell 351,0.56,Central,Minnesota,Prior Lake,55372,2010-05-12,2010-05-13,-37.0300,4,13.99,86838
22,24848,Medium,0.05,3.58,1.63,14,Gwendolyn F Tyson,Regular Air,Small Business,Office Supplies,Rubber Bands,Wrap Bag,"OIC Colored Binder Clips, Assorted Sizes",0.36,Central,Minnesota,Prior Lake,55372,2010-05-12,2010-05-13,-0.7100,4,14.26,86838
23,24845,Medium,0.01,6.48,7.86,14,Gwendolyn F Tyson,Regular Air,Small Business,Office Supplies,Paper,Small Box,Xerox 213,0.37,Central,Minnesota,Prior Lake,55372,2013-05-12,2013-05-13,-44.5400,4,29.55,86845

In [ ]:
#using iloc
dataFun =dataDf[dataDf['Product Category']== "Furniture"]
dataFun

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,Product Sub-Category,Product Container,Product Name,Product Base Margin,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
7,20228,Not Specified,0.02,500.98,26.00,5,Ronnie Proctor,Delivery Truck,Home Office,Furniture,Chairs & Chairmats,Jumbo Drum,Global Troy™ Executive Leather Low-Back Tilter,0.60,West,California,San Gabriel,91776,2010-12-13,2010-12-15,4390.366500,12,6362.85,90193
14,20876,Medium,0.08,140.98,36.09,8,Melanie Garner,Delivery Truck,Home Office,Furniture,Bookcases,Jumbo Box,"Sauder Forest Hills Library, Woodland Oak Finish",0.77,East,New Hampshire,Bedford,3110,2012-12-25,2012-12-26,-158.740000,5,705.47,90199
15,20877,Medium,0.10,286.85,61.76,9,Lorraine Houston,Delivery Truck,Home Office,Furniture,Tables,Jumbo Box,Riverside Furniture Stanwyck Manor Table Series,0.78,East,New Jersey,Camden,8101,2012-12-25,2012-12-27,-346.615198,8,1794.27,90199
17,21776,Critical,0.06,9.48,7.29,11,Marcus Dunlap,Regular Air,Home Office,Furniture,Office Furnishings,Small Pack,"DAX Two-Tone Rosewood/Black Document Frame, De...",0.45,East,New Jersey,Roselle,7203,2010-08-15,2010-08-17,-53.809600,22,211.15,90192
19,24844,Medium,0.09,78.69,19.99,14,Gwendolyn F Tyson,Regular Air,Small Business,Furniture,Office Furnishings,Small Box,Howard Miller 12-3/4 Diameter Accuwave DS ™ Wa...,0.43,Central,Minnesota,Prior Lake,55372,2010-05-12,2010-05-14,803.470500,16,1164.45,86838
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9408,22194,High,0.00,160.98,35.02,3398,Marc McDaniel,Delivery Truck,Small Business,Furniture,Bookcases,Jumbo Box,Rush Hierlooms Collection Rich Wood Bookcases,0.72,Central,Illinois,Decatur,62521,2012-11-25,2012-11-26,1790.426000,41,7158.10,87544
9413,24911,Medium,0.10,9.38,4.93,3400,Florence Gold,Express Air,Small Business,Furniture,Office Furnishings,Small Box,Eldon Expressions Punched Metal & Wood Desk Ac...,0.57,East,West Virginia,Fairmont,26554,2010-10-04,2010-10-04,-24.710400,15,135.78,87537
9420,18329,High,0.08,212.60,52.20,3402,Frederick Cole,Delivery Truck,Consumer,Furniture,Tables,Jumbo Box,Bush Advantage Collection® Round Conference Table,0.64,East,West Virginia,Charleston,25314,2011-04-12,2011-04-12,-513.790420,10,1969.31,87531
9423,24491,Not Specified,0.08,550.98,45.70,3402,Frederick Cole,Delivery Truck,Consumer,Furniture,Tables,Jumbo Box,Chromcraft Bull-Nose Wood Oval Conference Tabl...,0.71,East,West Virginia,Charleston,25314,2013-09-12,2013-09-14,-1225.029097,4,2215.93,87533
9424,25914,High,0.10,105.98,13.99,3403,Tammy Buckley,Express Air,Consumer,Furniture,Office Furnishings,Medium Box,"Tenex 46"" x 60"" Computer Anti-Static Chairmat,...",0.65,West,Wyoming,Cheyenne,82001,2010-02-08,2010-02-11,349.485000,5,506.50,87530

In [ ]:
#using loc
dataFun =dataDf.loc[dataDf['Product Category']== "Furniture"]
dataFun

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,Product Sub-Category,Product Container,Product Name,Product Base Margin,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
7,20228,Not Specified,0.02,500.98,26.00,5,Ronnie Proctor,Delivery Truck,Home Office,Furniture,Chairs & Chairmats,Jumbo Drum,Global Troy™ Executive Leather Low-Back Tilter,0.60,West,California,San Gabriel,91776,2010-12-13,2010-12-15,4390.366500,12,6362.85,90193
14,20876,Medium,0.08,140.98,36.09,8,Melanie Garner,Delivery Truck,Home Office,Furniture,Bookcases,Jumbo Box,"Sauder Forest Hills Library, Woodland Oak Finish",0.77,East,New Hampshire,Bedford,3110,2012-12-25,2012-12-26,-158.740000,5,705.47,90199
15,20877,Medium,0.10,286.85,61.76,9,Lorraine Houston,Delivery Truck,Home Office,Furniture,Tables,Jumbo Box,Riverside Furniture Stanwyck Manor Table Series,0.78,East,New Jersey,Camden,8101,2012-12-25,2012-12-27,-346.615198,8,1794.27,90199
17,21776,Critical,0.06,9.48,7.29,11,Marcus Dunlap,Regular Air,Home Office,Furniture,Office Furnishings,Small Pack,"DAX Two-Tone Rosewood/Black Document Frame, De...",0.45,East,New Jersey,Roselle,7203,2010-08-15,2010-08-17,-53.809600,22,211.15,90192
19,24844,Medium,0.09,78.69,19.99,14,Gwendolyn F Tyson,Regular Air,Small Business,Furniture,Office Furnishings,Small Box,Howard Miller 12-3/4 Diameter Accuwave DS ™ Wa...,0.43,Central,Minnesota,Prior Lake,55372,2010-05-12,2010-05-14,803.470500,16,1164.45,86838
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9408,22194,High,0.00,160.98,35.02,3398,Marc McDaniel,Delivery Truck,Small Business,Furniture,Bookcases,Jumbo Box,Rush Hierlooms Collection Rich Wood Bookcases,0.72,Central,Illinois,Decatur,62521,2012-11-25,2012-11-26,1790.426000,41,7158.10,87544
9413,24911,Medium,0.10,9.38,4.93,3400,Florence Gold,Express Air,Small Business,Furniture,Office Furnishings,Small Box,Eldon Expressions Punched Metal & Wood Desk Ac...,0.57,East,West Virginia,Fairmont,26554,2010-10-04,2010-10-04,-24.710400,15,135.78,87537
9420,18329,High,0.08,212.60,52.20,3402,Frederick Cole,Delivery Truck,Consumer,Furniture,Tables,Jumbo Box,Bush Advantage Collection® Round Conference Table,0.64,East,West Virginia,Charleston,25314,2011-04-12,2011-04-12,-513.790420,10,1969.31,87531
9423,24491,Not Specified,0.08,550.98,45.70,3402,Frederick Cole,Delivery Truck,Consumer,Furniture,Tables,Jumbo Box,Chromcraft Bull-Nose Wood Oval Conference Tabl...,0.71,East,West Virginia,Charleston,25314,2013-09-12,2013-09-14,-1225.029097,4,2215.93,87533
9424,25914,High,0.10,105.98,13.99,3403,Tammy Buckley,Express Air,Consumer,Furniture,Office Furnishings,Medium Box,"Tenex 46"" x 60"" Computer Anti-Static Chairmat,...",0.65,West,Wyoming,Cheyenne,82001,2010-02-08,2010-02-11,349.485000,5,506.50,87530

In [ ]:
#we can use loc to get records of more than one specific variables
#df.loc[(df['Product Category'] == 'Furniture') & (df['Order Date'] == '2010-07-07')]
dataDf.loc[(dataDf['Product Category'] == 'Furniture') & (dataDf['Order Date'] == '2010-07-07')]

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,Product Sub-Category,Product Container,Product Name,Product Base Margin,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
1639,25539,Critical,0.03,14.20,5.30,619,Howard Rogers,Regular Air,Consumer,Furniture,Office Furnishings,Wrap Bag,Coloredge Poster Frame,0.46,Central,Michigan,Southgate,48195,2010-07-07,2010-07-08,107.0200,14,205.98,88196
4805,19419,Low,0.03,5.08,2.03,1781,Jackie Capps,Regular Air,Home Office,Furniture,Office Furnishings,Wrap Bag,"Master Caster Door Stop, Brown",0.51,West,California,San Carlos,94070,2010-07-07,2010-07-12,15.1524,4,21.96,89858
8467,19739,Medium,0.00,137.48,32.18,3076,Peter Hardy,Delivery Truck,Small Business,Furniture,Bookcases,Jumbo Box,O'Sullivan Cherrywood Estates Traditional Barr...,0.78,East,Ohio,Stow,44224,2010-07-07,2010-07-08,-203.2700,2,296.75,88241
8492,1739,Medium,0.00,137.48,32.18,3079,Andrew Levine,Delivery Truck,Small Business,Furniture,Bookcases,Jumbo Box,O'Sullivan Cherrywood Estates Traditional Barr...,0.78,East,Pennsylvania,Philadelphia,19112,2010-07-07,2010-07-08,-203.2700,10,1483.76,12480

In [ ]:
#we can use tilde(~) to get the records of those not represented in the code
#df.loc[~((df['Product Category'] == 'Furniture') & (df['Order Date'] == '2010-07-07'))]

## query

Query method is another way of getting specific records

In [ ]:
?dataDf.query

In [ ]:
#getting specific records e.g df.query('Sales >200 and Region == "West"')
dataDf.query('Sales < 300 and Region=="West"')

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,Product Sub-Category,Product Container,Product Name,Product Base Margin,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
1,20847,High,0.01,2.84,0.93,3,Bonnie Potter,Express Air,Corporate,Office Supplies,Pens & Art Supplies,Wrap Bag,SANFORD Liquid Accent™ Tank-Style Highlighters,0.54,West,Washington,Anacortes,98221,2010-07-07,2010-07-08,4.56000,4,13.01,88522
2,23086,Not Specified,0.03,6.68,6.15,3,Bonnie Potter,Express Air,Corporate,Office Supplies,Paper,Small Box,Xerox 1968,0.37,West,Washington,Anacortes,98221,2011-07-27,2011-07-28,-47.64000,7,49.92,88523
3,23087,Not Specified,0.01,5.68,3.60,3,Bonnie Potter,Regular Air,Corporate,Office Supplies,"Scissors, Rulers and Trimmers",Small Pack,Acme® Preferred Stainless Steel Scissors,0.56,West,Washington,Anacortes,98221,2011-07-27,2011-07-28,-30.51000,7,41.64,88523
8,19483,Low,0.08,6.48,6.81,5,Ronnie Proctor,Regular Air,Home Office,Office Supplies,Paper,Small Box,Xerox 1930,0.36,West,California,San Gabriel,91776,2012-05-12,2012-05-21,-141.26000,18,113.25,90197
10,24563,Critical,0.07,6.48,6.60,6,Dwight Hwang,Regular Air,Home Office,Office Supplies,Paper,Small Box,Xerox 21,0.37,West,California,San Jose,95123,2012-12-29,2012-12-31,-13.86000,4,28.61,90200
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9388,19722,Critical,0.02,5.98,5.35,3393,Irene Murphy,Regular Air,Consumer,Office Supplies,Paper,Small Box,Xerox 1947,0.40,West,Washington,Pullman,99163,2013-10-18,2013-10-21,-70.85000,20,124.64,87914
9389,21333,Low,0.10,6.68,6.92,3394,Julia Padgett,Regular Air,Consumer,Office Supplies,Paper,Small Box,Xerox 1898,0.37,West,Washington,Puyallup,98373,2011-09-17,2011-09-24,-74.03000,9,57.22,87910
9390,23658,Medium,0.00,12.28,4.86,3394,Julia Padgett,Express Air,Consumer,Office Supplies,Paper,Small Box,Xerox 1933,0.38,West,Washington,Puyallup,98373,2012-03-10,2012-03-11,115.21620,13,166.98,87911
9391,22578,Not Specified,0.04,6.84,8.37,3394,Julia Padgett,Regular Air,Consumer,Office Supplies,"Scissors, Rulers and Trimmers",Small Pack,"Acme Design Line 8"" Stainless Steel Bent Sciss...",0.58,West,Washington,Puyallup,98373,2013-08-19,2013-08-20,-117.25296,24,161.87,87913
9425,24492,Not Specified,0.09,7.78,2.50,3403,Tammy Buckley,Express Air,Consumer,Office Supplies,Envelopes,Small Box,Staples #10 Colored Envelopes,0.38,West,Wyoming,Cheyenne,82001,2013-09-12,2013-09-14,78.06240,23,172.48,87533

In [ ]:
#Another different way of using query method
#min_sale = 600
#df.query('Sales > @min_sale and (Region == "West")')
#----------------------------------------------

## Summary Statistics

This is when we want to infer or get more information on the variable performance

In [ ]:
#we can use min, max, mean, std, and quantile
print(dataDf.Sales.mean())
print(dataDf.Sales.min())
print(dataDf.Sales.max())
print(dataDf.Sales.std())
print(dataDf.Sales.quantile([.25, .5, .75]))

949.7062720135795
1.32
100119.16
2598.0198182734284
0.25     61.2825
0.50    203.4550
0.75    776.4025
Name: Sales, dtype: float64

## agg

This is used when we need to get summary statistics of more than 1 at ago.

In [ ]:
# Getting  min, mean, max of 3 variables('Sales','Discount', 'Profit'), use  df[['col1','col2', 'col3']].agg(['mean', 'min', 'max'])
dataDf[['Sales','Discount', 'Profit']].agg(['mean', 'min', 'max'])

              Sales  Discount       Profit
mean     949.706272  0.049628    139.23641
min        1.320000  0.000000 -16476.83800
max   100119.160000  0.250000  16332.41400

In [ ]:
#another way of doing the above using key-value pair

## Summarize categoricals

we use different way to categorize categorical variables

In [ ]:
## Summarize categoricals

#use unique to see the unique values in the variable region
dataDf['Product Category'].unique()

array(['Office Supplies', 'Technology', 'Furniture'], dtype=object)

In [ ]:
#nunique is used to get the number
dataDf['Product Category'].nunique()

3

In [ ]:
#Value count is used to get the number of occurances use df['col'].value_counts()
dataDf['Product Category'].value_counts()

Product Category
Office Supplies    5181
Technology         2312
Furniture          1933
Name: count, dtype: int64

In [ ]:
# valuse counts for 2 variable, return dataframe  df[['col1', 'col2']].value_counts()

In [ ]:
# we use reset index so that the result starts from index zero use df[['col1', 'col2']].value_counts().reset_index()
dataFun =dataDf.loc[dataDf['Product Category']== "Furniture"].reset_index()
dataFun

,index,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,Product Sub-Category,Product Container,Product Name,Product Base Margin,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
0,7,20228,Not Specified,0.02,500.98,26.00,5,Ronnie Proctor,Delivery Truck,Home Office,Furniture,Chairs & Chairmats,Jumbo Drum,Global Troy™ Executive Leather Low-Back Tilter,0.60,West,California,San Gabriel,91776,2010-12-13,2010-12-15,4390.366500,12,6362.85,90193
1,14,20876,Medium,0.08,140.98,36.09,8,Melanie Garner,Delivery Truck,Home Office,Furniture,Bookcases,Jumbo Box,"Sauder Forest Hills Library, Woodland Oak Finish",0.77,East,New Hampshire,Bedford,3110,2012-12-25,2012-12-26,-158.740000,5,705.47,90199
2,15,20877,Medium,0.10,286.85,61.76,9,Lorraine Houston,Delivery Truck,Home Office,Furniture,Tables,Jumbo Box,Riverside Furniture Stanwyck Manor Table Series,0.78,East,New Jersey,Camden,8101,2012-12-25,2012-12-27,-346.615198,8,1794.27,90199
3,17,21776,Critical,0.06,9.48,7.29,11,Marcus Dunlap,Regular Air,Home Office,Furniture,Office Furnishings,Small Pack,"DAX Two-Tone Rosewood/Black Document Frame, De...",0.45,East,New Jersey,Roselle,7203,2010-08-15,2010-08-17,-53.809600,22,211.15,90192
4,19,24844,Medium,0.09,78.69,19.99,14,Gwendolyn F Tyson,Regular Air,Small Business,Furniture,Office Furnishings,Small Box,Howard Miller 12-3/4 Diameter Accuwave DS ™ Wa...,0.43,Central,Minnesota,Prior Lake,55372,2010-05-12,2010-05-14,803.470500,16,1164.45,86838
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1928,9408,22194,High,0.00,160.98,35.02,3398,Marc McDaniel,Delivery Truck,Small Business,Furniture,Bookcases,Jumbo Box,Rush Hierlooms Collection Rich Wood Bookcases,0.72,Central,Illinois,Decatur,62521,2012-11-25,2012-11-26,1790.426000,41,7158.10,87544
1929,9413,24911,Medium,0.10,9.38,4.93,3400,Florence Gold,Express Air,Small Business,Furniture,Office Furnishings,Small Box,Eldon Expressions Punched Metal & Wood Desk Ac...,0.57,East,West Virginia,Fairmont,26554,2010-10-04,2010-10-04,-24.710400,15,135.78,87537
1930,9420,18329,High,0.08,212.60,52.20,3402,Frederick Cole,Delivery Truck,Consumer,Furniture,Tables,Jumbo Box,Bush Advantage Collection® Round Conference Table,0.64,East,West Virginia,Charleston,25314,2011-04-12,2011-04-12,-513.790420,10,1969.31,87531
1931,9423,24491,Not Specified,0.08,550.98,45.70,3402,Frederick Cole,Delivery Truck,Consumer,Furniture,Tables,Jumbo Box,Chromcraft Bull-Nose Wood Oval Conference Tabl...,0.71,East,West Virginia,Charleston,25314,2013-09-12,2013-09-14,-1225.029097,4,2215.93,87533
1932,9424,25914,High,0.10,105.98,13.99,3403,Tammy Buckley,Express Air,Consumer,Furniture,Office Furnishings,Medium Box,"Tenex 46"" x 60"" Computer Anti-Static Chairmat,...",0.65,West,Wyoming,Cheyenne,82001,2010-02-08,2010-02-11,349.485000,5,506.50,87530

## shift, cumsum

In [ ]:
#shift is commonly used in time series , use df[['col']].shift(1)

In [ ]:
#shift last value df[['col']].shift(-1)

In [ ]:
#shift last value df[['col']].shift(-1)

In [ ]:
#summing up the sum values, use df[['col']].cumsum()

## Rolling methods

In [ ]:
#using Rolling, usse df[['col']].rolling(window=5).mean()

## Groupby

This is used when we want to summarize categorical features based on a certain numerical variable

In [ ]:
# use groupby, use df.groupby('cat_col')[['num_coll']].mean(), e.g region and sales
dataDf.groupby("Region")[["Sales"]].mean()

               Sales
Region
Central   876.282035
East     1058.455518
South     817.475036
West     1047.039755

In [ ]:
#combining two numerical columns df.groupby('col1')[['col2', 'col3']].agg(["mean", "min"])

## New columns

In [ ]:
## New columns cost, by subtracting sales frm profit

dataDf["cost"] = dataDf["Sales"] - dataDf["Profit"]
dataDf.head()

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,Product Sub-Category,Product Container,Product Name,Product Base Margin,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID,cost
0,18606,Not Specified,0.01,2.88,0.50,2,Janice Fletcher,Regular Air,Corporate,Office Supplies,Labels,Small Box,Avery 49,0.36,Central,Illinois,Addison,60101,2012-05-28,2012-05-30,1.3200,2,5.90,88525,4.5800
1,20847,High,0.01,2.84,0.93,3,Bonnie Potter,Express Air,Corporate,Office Supplies,Pens & Art Supplies,Wrap Bag,SANFORD Liquid Accent™ Tank-Style Highlighters,0.54,West,Washington,Anacortes,98221,2010-07-07,2010-07-08,4.5600,4,13.01,88522,8.4500
2,23086,Not Specified,0.03,6.68,6.15,3,Bonnie Potter,Express Air,Corporate,Office Supplies,Paper,Small Box,Xerox 1968,0.37,West,Washington,Anacortes,98221,2011-07-27,2011-07-28,-47.6400,7,49.92,88523,97.5600
3,23087,Not Specified,0.01,5.68,3.60,3,Bonnie Potter,Regular Air,Corporate,Office Supplies,"Scissors, Rulers and Trimmers",Small Pack,Acme® Preferred Stainless Steel Scissors,0.56,West,Washington,Anacortes,98221,2011-07-27,2011-07-28,-30.5100,7,41.64,88523,72.1500
4,23088,Not Specified,0.00,205.99,2.50,3,Bonnie Potter,Express Air,Corporate,Technology,Telephones and Communication,Small Box,V70,0.59,West,Washington,Anacortes,98221,2011-07-27,2011-07-27,998.2023,8,1446.67,88523,448.4677

In [ ]:
#Another way of creating new column using assign method, use df=df.assign(colname=expression)
#creating new column using .assign()   #df=df.assign(col_2=df["Profit"]/0.3)

## Sorting

This is a way of ordering the values either in ascending or descending order

In [ ]:
#sort values use  df.sort_values('col'), we can apply argument ascending= False to get the result in descending order
#df.sort_values('Region', ascending=False)
dataf = dataDf.groupby("Region")[["Sales"]].mean()
dataf.sort_values('Sales', ascending=False)

               Sales
Region
East     1058.455518
West     1047.039755
Central   876.282035
South     817.475036

In [ ]:
#resetting the index, use df[['col1', 'col2', 'col3']].sort_values('col3', ascending=False).reset_index(drop=True)
#df[['Region',"Product Name","Sales"]].sort_values("Sales", ascending=False)

## Missing data

This is how we can check and fix null values

In [ ]:
#fixing the null values  by dropping the rows df.dropna(subset=['col with missing value']), or just df.dropna() for entire dataframe
df.dropna(inplace=True)
df.isna().sum()

In [ ]:
#filling up the missing value with specific value, use df[['col1', 'col2', 'col3']].fillna(0)

In [ ]:
#Filling with the mean of the column, use df['col1'].fillna(df['col1'].mean())

## Concat

concat is used when all the variables as similar

In [ ]:
# create 2 dataframe
#df1 = df.query('Region == "West"').copy()
#df2 = df.query('Region == "East"').copy()

In [ ]:
#concat, use pd.concat([df1, df2])

In [ ]:
#we can resset the index then concat as well
df1 = df1.reset_index(drop=True)
df2 = df2.reset_index(drop=True)

In [ ]:
#concat, use pd.concat([df1, df2], axis=1)
df_concat=pd.concat([df1,df2], axis=1)
df_concat.head()

## Merge dataframes

In [ ]:
#create 2 dataframe
df1 = df.groupby(['Region', 'Order Date'])[['Sales']].mean().reset_index()
df2 = df.groupby(['Region', 'Order Date'])[['Profit']].mean().reset_index()

In [ ]:
## Merge dataframes#merge left, use df1.merge(df2, how="left")
df1.merge(df2,how='left')

In [ ]:
#merge on right, use df1.merge(df2, how="right")

In [ ]:
#merging on outer, use df1.merge(df2, how="outer")

## Merge suffixes

In [ ]:
#merging using suffices use, pd.merge(df1, df2, on=['col1', 'col2'])

In [ ]:
#merge on specific similar column use pd.merge(df1, df2, on=df['col1'])

In [ ]:
#merging using both letf and right on,use pd.merge(df1, df2, left_on=['col1'], right_on=['col1'])